### ISSUE TITLE
examples give syntax error

### ISSUE THREAD

**Issue by andreaschizzali** [web2py/py4web#101]
Today I installed pi4web from source on a Windows 8.1 system. I have python 3.7 installed, I had to change the commands using python instead of python3 in the line 
    python3 -m pip install -r requirements.txt
an in the next line I had to prepend a "python " before the line
    ./py4web-start.py apps
then all worked apparently well.
After the installation I creates a new application from the scaffold and then I modified the __init__.py and then I saved the file. Immediately the icon of the examples button begun to blink in red. 
The error messages are as follows:

Traceback (most recent call last):
  File "C:\AC\py4web\py4web\core.py", line 839, in import_app
    importlib.reload(sys.modules[name])
  File "C:\Program Files\Python37\lib\importlib\__init__.py", line 169, in reload
    _bootstrap._exec(spec, module)
  File "<frozen importlib._bootstrap>", line 630, in _exec
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "apps\examples\models.py", line 12, in <module>
    Field("job", requires=IS_NOT_EMPTY(), label=T('job')),
  File "C:\Program Files\Python37\lib\site-packages\pydal\base.py", line 642, in define_table
    raise SyntaxError("table already defined: %s" % tablename)
  File "<string>", line None
SyntaxError: table already defined: person

I deleted the installatoin and reinstalled the whole thing, all went well. Now I opened the __init__.py of the _dashboard application, made no changes and simply saved the file, I otained the same error in examples as before. 
So it seems that the error does not lie in my modifications.
Kind regards.

**Comment by andreaschizzali** [comment]
Here are some details about my installation:
python  |  3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 22:22:05) [MSC v.1916 64 bit (AMD64)]
py4web  |  0.1.20191229.1

**Comment by andreaschizzali** [comment]
I closed the issue by mistake, I'm a newbie, have little experience with python and none with web2py. I have only watched some older videos on youtube about web2py. 
Now  I tried with the new, apparently simpler py4web, but stumbled on a probably little problem on the first try. I hope to learn something.

**Comment by mdipierro** [comment]
Please check that you have db.commit() at the end of the file apps/examples/models.py
If not do:

rm -rf apps/examples
python3 -m pip install -U py4web # to upgrade py4web
py4web -c apps # to upgrate the mssing app

**Comment by andreaschizzali** [comment]
Many thanks
