### ISSUE TITLE
Shell support

### ISSUE THREAD

**Issue by misl6** [web2py/py4web#102]
Seen this repo a quite ago, but I just started testing out today for a upcoming project. (Currently I'm a "everyday" **web2py** user).

**py4web** seems to be very promising, and truly faster compared to **web2py**, so I'm looking forward to use it in production soon :)  .

As a **web2py** user I'm used to have access to the "web2py shell" (`./web2py.py -M -S app_name`), which during the past few years was very useful during debugging or maintenance.

Is that an expected functionality in **py4web** ?

**Comment by mdipierro** [comment]
py4web is better. Apps are just modules therefore you can just do:

python3
>>> from apps.myapp.models import db
>>> rows = db(....).select()
