### ISSUE TITLE
Typo in docs

### ISSUE THREAD

**Issue by Eddiedigits** [web2py/py4web#103]
Couple of Typo's I noticed while reading the docs.

From _scaffold
Most of the times, you do not want to start writing code from scratch. You also want to follow **some sane** (the same) conventions outlined here, like not putting all your code into __init__.py. PY4WEB provides a Scaffolding (_scaffold) app, where files are organized properly and many useful objects are pre-defined.

Notice that static is a special path for py4web and only files under the static folder are served.
To create a dynamic page, you must create a function that returns the page content. For example **dit** (edit) the myapp/__init__.py as follows:

**Comment by Eddiedigits** [comment]
### Custom fixtures
The transform function is called to perform any desired transformation of the **valute** (value) returned by the index() function.

**Comment by Eddiedigits** [comment]
### Tags and Permissions
We leave it to you as an **exersize** (exercise) to create a fixture has_membership to enable the following syntax:

**Comment by nicozanf** [comment]
Hi, this should be closed by 034629316a9a78d19f08fc8bf1e891fff5be6ad1 . Thank you!
