### ISSUE TITLE
MySQL server has gone away

### ISSUE THREAD

**Issue by sfiorenz** [web2py/py4web#107]
Hi!

I created an app on PythonAnywhere and when I access a very simple controller, with only T as the fixture, I often get this error

Error Ticket: (2006, 'MySQL server has gone away')

Traceback (most recent call last):
  File "/home/simonefiorenzoni/.local/lib/python3.8/site-packages/py4web/core.py", line 502, in wrapper
    [obj.on_request() for obj in fixtures]
  File "/home/simonefiorenzoni/.local/lib/python3.8/site-packages/py4web/core.py", line 502, in <listcomp>
    [obj.on_request() for obj in fixtures]
  File "/home/simonefiorenzoni/.local/lib/python3.8/site-packages/py4web/utils/auth.py", line 36, in on_request
    self.abort_or_rediect("login")
  File "/home/simonefiorenzoni/.local/lib/python3.8/site-packages/py4web/utils/auth.py", line 29, in abort_or_rediect
    redirect(URL(self.auth.route, page))
  File "/home/simonefiorenzoni/.local/lib/python3.8/site-packages/py4web/core.py", line 467, in redirect
    raise HTTP(303)
py4web.core.HTTP: 303

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/simonefiorenzoni/.local/lib/python3.8/site-packages/py4web/core.py", line 543, in wrapper
    ret = func(*func_args, **func_kwargs)
  File "/home/simonefiorenzoni/.local/lib/python3.8/site-packages/py4web/core.py", line 509, in wrapper
    [obj.on_success() for obj in fixtures]
  File "/home/simonefiorenzoni/.local/lib/python3.8/site-packages/py4web/core.py", line 509, in <listcomp>
    [obj.on_success() for obj in fixtures]
  File "/home/simonefiorenzoni/.local/lib/python3.8/site-packages/py4web/core.py", line 244, in on_success
    self.commit()
  File "/home/simonefiorenzoni/.local/lib/python3.8/site-packages/pydal/base.py", line 794, in commit
    self._adapter.commit()
  File "/home/simonefiorenzoni/.local/lib/python3.8/site-packages/pydal/adapters/__init__.py", line 57, in wrap
    return f(*args, **kwargs)
  File "/home/simonefiorenzoni/.local/lib/python3.8/site-packages/pydal/adapters/base.py", line 978, in commit
    return self.connection.commit()
MySQLdb._exceptions.OperationalError: (2006, 'MySQL server has gone away')

**Comment by mahbubcubd** [comment]
We were facing the same issue. Restarting uwsgi fixes this. We took a terrible decision. To keep the MySQL session, we ran a cronjob that restarts the uwsgi in every 5 minutes. however, this is fine for now since there is a little traffic on our website right now. 
I am eagerly waiting for this fix.

**Comment by sfiorenz** [comment]
Hi Mahbubcubd,
I can confirm that I also do exactly the same to solve. Luckily my application is (still) just a test...

**Comment by sfiorenz** [comment]
> 
> 
> We were facing the same issue. Restarting uwsgi fixes this. We took a terrible decision. To keep the MySQL session, we ran a cronjob that restarts the uwsgi in every 5 minutes. however, this is fine for now since there is a little traffic on our website right now.
> I am eagerly waiting for this fix.

**Comment by sfiorenz** [comment]
> 
> 
> We were facing the same issue. Restarting uwsgi fixes this. We took a terrible decision. To keep the MySQL session, we ran a cronjob that restarts the uwsgi in every 5 minutes. however, this is fine for now since there is a little traffic on our website right now.
> I am eagerly waiting for this fix.

Hi Mahbubcubd,
I can confirm that I also do exactly the same to solve. Luckily my application is (still) just a test...

**Comment by mdipierro** [comment]
Does this help?
https://stackoverflow.com/a/9479681

**Comment by sfiorenz** [comment]
I can't change the mysql configuration in pythonanywehere. The current configuration is max_allowed_packet = 16000000

But I think it could be a problem of connections that somehow expire. 
I also noticed another issue: if I refresh the py4web dashboard, at every refresh the connections to the mysql server are added, up to saturate the maximum allowed (my account include a maximum of 5) ... and also in that case I have to terminate them or reload the wsgi application.

**Comment by mahbubcubd** [comment]
I have executed this command in MySQL shell yesterday
set global max_allowed_packet=268435456;
I am not getting a connection error anymore. Please try it.

Note: in my.cnf under [mysqld] max_allowed_packet=268435456 has already been there. Now just set it to global

**Comment by mahbubcubd** [comment]
It's not working. py4web is showed me the same error today.

**Comment by sfiorenz** [comment]
I can't change that value of global max_allowed_packet, the mysql console says I'm not authorized.

The problem for me seems to be related to some kind of timeout that expires, I can't say at what level. If I browse the pages of my site at regular intervals the problem does not occur. 
If I wait more than 4-5 minutes then this problem happens.

**Comment by sfiorenz** [comment]
Still no solution? 
I have seen that the scheduled tasks are not affected by this problem, it seems that the timeout that occurs is not at the DAL level. I suspect that in those cases it try to access a connection in the pool already terminated by the DAL.

**Comment by jpsteil** [comment]
I believe this has been resolved and can be closed

**Comment by sfiorenz** [comment]
I haven't figured it out yet. 
Maybe mahbubcubd solved it?

**Comment by jpsteil** [comment]
sfiorenz - are you still having the issue?  I thought Massimo addressed this some time ago.  If so, are you using the latest py4web from git?

**Comment by sfiorenz** [comment]
No, I have not updated. I will try and give you some feedback. Thank you!

**Comment by sfiorenz** [comment]
I confirm that the problem is solved. Thanks a lot to Massimo and all of you!
