### ISSUE TITLE
Each worker has own session?

### ISSUE THREAD

**Issue by valq7711** [web2py/py4web#108]
https://github.com/web2py/py4web/blob/830c76a2222d0a62a37bea8a5bdbfd9bbb5ddda4/py4web/core.py#L331

In case of usage multiple workers, each worker will have its own secret  i.e. own session! (If `secret`-argument is not provided).
I got this issue on gunicorn with gevent workers. 
Could we store `uuid` key in `os.environ` to share secret between workers? 

UPDATE:
As variant, we can store in os.environ only the flag like `secret_is_generated`, if it is not set then uuid-secret should be generated and stored in some file, otherwise, the `secret` should be read from that file.

**Comment by mdipierro** [comment]
This is a serious bug. Will address tomorrow.
