### ISSUE TITLE
scheme of url shows http when used behind https proxy

### ISSUE THREAD

**Issue by crc1021** [web2py/py4web#113]
When using py4web with a proxy (py4web running on port 8000, web server frontend is https), the scheme within py4web is showing http even through the url is https.
The OAUTH class uses the scheme internally which affects the URIs it creates (makes http URIs when site is https).  
Also, it might be nice to have ability to simply specify scheme of URI
```
class OAuth2(SSO):
    ...
    def __init__(self, client_id, client_secret, callback_url, scope=None, scheme=True):
    ....
```
reference: https://groups.google.com/forum/#!topic/web2py/ZGANNSBBJZM

**Comment by valq7711** [comment]
what is the frontend?
You need to set `X-Forwarded-Proto` - header
for nginx:
`proxy_set_header X-Forwarded-Proto $scheme;`

if you can't set header,  it is better to write wsgi-middle-fixer as at bottle FAQ suggested, 
since it is proxy-server issue, not py4web/bottle

@mdipierro  - can be closed
