### ISSUE TITLE
404 returned on import errors etc

### ISSUE THREAD

**Issue by lucadealfaro** [web2py/py4web#115]
If there is an error, such an import error, in a controller, py4web responds with an error 404, and nothing useful is logged anywhere I can see.  This makes finding errors somewhat hard.  Is there any way in which this can be improved?

**Comment by mdipierro** [comment]
Sorry for the late reply. Unlike web2py, in py4wb modules are reloaded when they change. import errors are detected in this way and they result in no-code being executed. In particular the actions are not defined. The error should be logged in the dashboard and on console. Is it not?

**Comment by mdipierro** [comment]
Sorry for the late reply. Unlike web2py, in py4wb modules are reloaded when they change. import errors are detected in this way and they result in no-code being executed. In particular the actions are not defined. The error should be logged in the dashboard and on console. Is it not?
