### ISSUE TITLE
Problem with globals().get('user') in layout.html

### ISSUE THREAD

**Issue by mahbubcubd** [web2py/py4web#121]
globals().get('user') returns **None** even after user logged in. As a result, 'sign in' option never disappers.

However, I noticed something.

- In any controller function, if I define any variable that contains auth.get_user() and then if I **return locals()** or return **dict(user=auth.get_user())**  then **globals().get('user')** be logically true and the  "sign in" option disappers and shows user session based menus in the menubar.

This seems inconvenient to me. When a user is in session, globals should automatically store globals().get('user'). Nor I have to define auth.get_user()  each time for every controller function.

Thank U

**Comment by valq7711** [comment]
What is `globals().get_user()`?
Maybe you mean  `globals().get('user')`?

**Comment by mahbubcubd** [comment]
> What is `globals().get_user()`?
> Maybe you mean `globals().get('user')`?

Sorry, my bad. I edited my title and message. However, I didn't change anything in layout.html
So the issue is about returning None.

**Comment by valq7711** [comment]
`auth.get_user()` may touches db, which may affect performance.
Instead of `auth.get_user()` in each controller you can make you own decorator like `@with_user` that will inject `user = auth.get_user()` in the result-dict
