### ISSUE TITLE
Create a generic JS that can generate forms based on API andpoint

### ISSUE THREAD

**Issue by mdipierro** [web2py/py4web#13]

**Comment by yamandu** [comment]
I would like to do this but I have some questions.

I understand this endpoint will provide a form schema for the form creation.
My question is: where will this schema com from?
From the DAL model with a default endpoint? 
From a user defined endpoint?
From a template file?

Some considerations I have:
-there are some vue components that already do similar; they create forms based on json schemas. Should we use any?
-I would be nice to have some kind of template for forms (and maybe even other components), so the styling could be easily changed without need to code.

**Comment by Kkeller83** [comment]
Schema should be DAL defintion I think

then a CRUD API decorator (similiar to SQLFORM.grid now) over the model in
the controller,
that automatically generates the crud functions and routes.
Another optional security decorator for CRUD API authtentication and role
based access would be important, most importantny via JWT token,
but down the line OAUTH2 with JWT, SAML2 etc. should be consindered I
think.

The decorator should also generate an openapi/swagger json file.

That file can be used as a basis to generate the Vue.js front end/form, but
can also be used for any other frontend JS framework such as React or
Angular.
In our case, if we were to scaffold and we set Vue as our framework of
choice, that swagger file should be the basis for each scaffolding of the
Vue frontend.
I suppose the openapi json file can sit somewhere in a separate folder or
in the controllers folder. A separate folder would be cleaner though.
The JSON for form generationr could also be saved in the DB as alterantive
(Postegres JSON store or Mongo/CouchDB etc.).

**Comment by mdipierro** [comment]
It is mostly done /_dashboard/static/components/mtable

**Comment by mdipierro** [comment]
Closing this since defects are better handled in more specific tickets
