### ISSUE TITLE
_scaffold app and auth url odd behavior

### ISSUE THREAD

**Issue by carpaIdea** [web2py/py4web#133]
When auth is invoked the initial url is "http://127.0.0.1:8000/_scaffold/auth/login?next=/_scaffold"
If the user goes to the registration page the url becomes "http://127.0.0.1:8000/_scaffold/auth/login?next=/register"

Shouldn't it be "http://127.0.0.1:8000/_scaffold/auth/register" instead?

The following modification could be made to the auth.js file but this may not be the right way to proceed.

_scaffold/static/component/auth.js Line 19 replaced with:

```
//var url = window.location.href.substring(0, window.location.href.lastIndexOf('/')) + '/' + page;
var url_noqs = window.location.href.split('?')[0] ;
var url = url_noqs.substring(0, url_noqs.lastIndexOf('/')) + '/' + page;
if (page == 'login') url += '?next=' + this.next ;
```

**Comment by misl6** [comment]
Your fix works fine, and that one seems to me the right place where making this change.

**Comment by carpaIdea** [comment]
thank you  for your prompt response.

Il giorno sab 28 mar 2020 alle ore 17:52 Mirko <notifications@github.com>
ha scritto:

**Comment by jpsteil** [comment]
I believe this can be closed.
