### ISSUE TITLE
Publisher grid - vue 2.6.11 warnings in mtable template

### ISSUE THREAD

**Issue by carpaIdea** [web2py/py4web#145]
py4web is shipped with version 2.2.0 of vue. If the latest version, 2.6.11, is used, there are the following alerts.
![tewmplate_warnings](https://user-images.githubusercontent.com/3496662/78463916-27773900-76e3-11ea-951d-6d8749c883f6.png)
Although there are no apparent side-effects in the current implementation of mtable, this should be taken into account in case of future changes to the grid function in the Publisher class.

**Comment by mdipierro** [comment]
this was addessd. thanks
