### ISSUE TITLE
Wrong version 1.20200329.1 on PyPI

### ISSUE THREAD

**Issue by luphord** [web2py/py4web#146]
On [PyPI](https://pypi.org/project/py4web/1.20200329.1/), there is a release `1.20200329.1` from 2020-03-30 which I assume should be `0.1.20200329.1` instead. If future versions starting with `0.1.x` are released, this `1.20200329.1` would still remain latest. I am not sure if this release can be reverted by any means.

**Comment by mdipierro** [comment]
I intentionally dropped the 0. I am adopting x.y.z where x indicates a major release that breaks backward compatibility, y is the date, and z is for multiple releases on the same date.

**Comment by luphord** [comment]
Ok, I see. Then everything is fine. However, major version 1 suggested a *stable* version to me while the [README](https://github.com/web2py/py4web#tell-me-more) indicates that py4web is *close to being stable*. You might want to add your comment above to the README.

**Comment by mdipierro** [comment]
Good point. Will do!
