### ISSUE TITLE
pydal DB_URI=google:datastore error 

### ISSUE THREAD

**Issue by jparga** [web2py/py4web#162]
Trying to set "google:datastore" database in settings.py: 
`DB_FOLDER = os.path.join(APP_FOLDER, "databases")

DB_URI = "google:datastore"  
DB_POOL_SIZE = 1` 

get this error:
`Traceback (most recent call last): File "/env/lib/python3.7/site-packages/pydal/base.py", line 507, in __init__ self._adapter = adapter(**kwargs) File "/env/lib/python3.7/site-packages/pydal/adapters/__init__.py", line 41, in __call__ obj = super(AdapterMeta, cls).__call__(*args, **kwargs) File "/env/lib/python3.7/site-packages/pydal/adapters/base.py", line 73, in __init__ self._load_dependencies() File "/env/lib/python3.7/site-packages/pydal/adapters/base.py", line 93, in _load_dependencies self.dialect = dialects.get_for(self) File "/env/lib/python3.7/site-packages/pydal/helpers/_internals.py", line 22, in get_for raise ValueError("no %s found for object: %s" % (self.namespace, obj)) ValueError: no dialect found for object: <pydal.adapters.google.GoogleDatastore object at 0x3e47b197b810>`

**Comment by mdipierro** [comment]
This is a known pydal issue. Closing here because it will be dealt with in pydal.
