### ISSUE TITLE
dashboard view issue

### ISSUE THREAD

**Issue by auden-rovellequartz** [web2py/py4web#168]
Two comments/issues:

The "databases" dropdown tab for the dashboard view seems to only show a maximum of 27 tables. I think it would be good that either scrolling is implemented such that a person can scroll down and see all the tables, or that the dashboard shows all the tables.

The "databases" dropdown tab for the dashboard view seems to not have horizontal scrollbar such that a person can see all fields in a table if the table has many fields. I think such scrolling would be good to implement.

**Comment by mdipierro** [comment]
I can fix the second problem but there should not be limit to 27 tables.
Very strange. Maybe it's a limit to the max div height. Will look
