### ISSUE TITLE
Py4web upload fields not uploading

### ISSUE THREAD

**Issue by Eudorajab1** [web2py/py4web#169]
Using field of type upload is not working and there seem to be a number of issues to resolve:
I spent a few hours looking into this and issues seem to be in the forms.py module and have hacked a fix as follows hope it helps:
circa line 63 in forms.py
elif field.type == "upload":
            control = DIV(INPUT(_type="file", _id=input_id, _name=field.name))
            if value:
                img = '''<img src="%s" class="img-thumbnail" alt="Image" width="304" height="236">''' % "../static/uploads/%s" % vars[field.name]
                control.append(XML(img))
                control.append(
                    INPUT(_type="checkbox", _value="ON", _name="_delete_" + field.name)
                    )
                control.append("(check to remove)")

forms.py circa line 248

if field.type == "upload":
                                value = request.files.get(field.name)
                                delete = post_vars.get("_delete_" + field.name)
                                if value is not None and hasattr(value, "file"):
                                    value = field.store(
                                        value.file, value.filename, field.uploadfolder
                                    )
                                elif self.record and not delete:
                                    value = self.record.get(field.name)
                                else:
                                    value = None
                            self.vars[field.name] = value
                            if error:
                                self.errors[field.name] = error 
This seems to work for me but with the following caveats:-I
1: uploads folder needs to be in app_name/static directory so app_name/static/uploads
2 My upload Field definition looks like 
Field('image', 'upload', uploadfolder="apps/erp_app/static/uploads/")

I think the reason for this is that a route in bottle needs to be set for the default app/uploads folder in which case a much more generic solution can be provided.

As I said this is pretty much a hack but hopefully will point you in the right direction for a proper fix.

**Comment by villas** [comment]
Eudorajab1,  You are right about using request.files,  this is what I did to my form.py

It seems that Bottle uses request.forms for normal form elements.
However, file data is stored in request.files.

I have therefore patched my form.py as follows (around line 250)

    if field.type == "upload":
        delete = post_vars.get("_delete_" + field.name)
        fvalue = request.files.get(field.name)
        if fvalue is not None and hasattr(fvalue, "file"):
            value = field.store(
                fvalue.file, fvalue.filename, field.uploadfolder
            )

**Comment by valq7711** [comment]
Should be fixed by https://github.com/web2py/py4web/commit/7b47dc492b11e651350baefcc194bc678b06fc01
