### ISSUE TITLE
Helpers Functionality vs Documentation

### ISSUE THREAD

**Issue by auden-rovellequartz** [web2py/py4web#171]
referencing the following resource:

http://py4web.com/_documentation/static/index.html#chapter-08

It seems to me that the helpers in the following list are not currently supported:

[
     COL,
     FIELDSET,
     LEGEND,
     SCRIPT,
     STYLE,
     THEAD,
     TT,
     ]

Maybe they should be either removed from the "yatl Helpers" page in the Py4web documentation (http://py4web.com/_documentation/static/index.html#chapter-08) or added to the list of supported yatl helpers

my current work-around is to just use the TAG helper as needed for those currently unsupported items.

**Comment by mdipierro** [comment]
added some of them to yatl 20200430.1.
For COL, FIELDSET, LEGENT please define them yourself where needed:

COL, FIELDSET, LEGEND = TAG.col, TAG.fieldset, TAG.legend

**Comment by auden-rovellequartz** [comment]
low priority, but maybe good idea to remove those three from
http://py4web.com/_documentation/static/index.html#chapter-08 to
sync documentation (since those will not be yatl helpers)

if you agree I will do pull request

**Comment by mdipierro** [comment]
yes. please
