### ISSUE TITLE
Dashboard does not allow the upload of a replacement app

### ISSUE THREAD

**Issue by lucadealfaro** [web2py/py4web#172]
To reproduce: 
- Create an app (you can clone the template) with any name, e.g., hw4blah. 
- Then, try to upload a .zip file, specifying hw4blah as name of the app, and "Replace" instead of "new  App". 

The dashboard loads the new app, then hangs.

**Comment by mdipierro** [comment]
Problem is a bottle limit with upload file size. Increasing to 16MB

**Comment by mdipierro** [comment]
This should be fixed.
