### ISSUE TITLE
Cannot run py4web from pip under Windows 10

### ISSUE THREAD

**Issue by nmarusov** [web2py/py4web#190]
(.venv) PS D:\py4web_pip> python -m pip install -U py4web
...
(.venv) PS D:\py4web_pip> py4web.exe --help
failed to create process.

From source all is OK:
(.venv) PS D:\py4web_src> python setup.py build
(.venv) PS D:\py4web_src> python setup.py install
(.venv) PS D:\py4web_src> py4web.exe --help
Usage: py4web [OPTIONS] COMMAND [ARGS]...

Options:
  --help  Show this message and exit.

Commands:
  call
  run
  set-password
  setup
  shell
  version

**Comment by mdipierro** [comment]
@nmarusov Do not have access to a windows machine. Can you us fix this?

**Comment by nicozanf** [comment]
@nmarusov : it seems a python / pip problem. Try it again. If you still have similar problems, look [here ](https://stackoverflow.com/questions/17373265/pip-easy-install-failure-failed-to-create-process)for possible solutions

**Comment by nicozanf** [comment]
I think this issue can be closed ....
