### ISSUE TITLE
Form fields

### ISSUE THREAD

**Issue by duskmaiden18** [web2py/py4web#201]
Hello, i have some trouble with Form.
I have this form for table: form1 = Form(db.auth_user, auth_user, deletable=False, formstyle=FormStyleBulma). How can I choose what fields I want to show? In web2py there was argument 'fields', where I can choose, but in py4web there is no argument such 'fields'.

**Comment by jpsteil** [comment]
Try:

db.tablename.fieldname.writable = False

...before callingn FORM()

to eliminate your field from the form.

-Jim

**Comment by duskmaiden18** [comment]
thank you, it works
