### ISSUE TITLE
Watchgod issues

### ISSUE THREAD

**Issue by pdralston** [web2py/py4web#202]
With the latest pull, watchgod is enabled. I have observed 2 issues with it so far.
1. When running the server using anaconda prompt, pressing Ctrl+C fails to interrupt the server as expected. Pressing the command twice seems to shut down the server as expected. This behavior is not observed when using WSL or PyCharm
2. When testing watchgod functionality, I changed a minor value in a python value, the watcher saw the change and reported that it reloaded the application in question. Upon hard refreshing I get a 500 error. Restarting the server manually allows the application to load in the browser as expected.

**Comment by pdralston** [comment]
![pycharm_setup_9](https://user-images.githubusercontent.com/25166909/82371015-56fdae80-99ce-11ea-9e2a-4d9489363d64.png)

**Comment by chbdetta** [comment]
> When running the server using anaconda prompt, pressing Ctrl+C fails to interrupt the server as expected. Pressing the command twice seems to shut down the server as expected. This behavior is not observed when using WSL or PyCharm

I think this happens only when WSGI server is used and it probably relates to the threads not exiting. 

> When testing watchgod functionality, I changed a minor value in a python value, the watcher saw the change and reported that it reloaded the application in question. Upon hard refreshing I get a 500 error. Restarting the server manually allows the application to load in the browser as expected.

the --watch option basically just uses the Reloader to reload apps after files change. So this bug should be able to be reproduced using the dashboard reload button.

**Comment by pdralston** [comment]
Commented on the commit. Shutting down the server when using anaconda still requires two keyboard interrupts.

**Comment by pdralston** [comment]
@chbdetta On reloading the apps, it is not able to be duplicated from the _dashboard because the dashboard is reloading all apps, not just the singular that was changed. It appears that there is some conflict that is raised by only reloading a singular app.

**Comment by pdralston** [comment]
![watcher_issue](https://user-images.githubusercontent.com/25166909/82845467-967a3e00-9e99-11ea-966a-076177f1d9cf.gif)

**Comment by pdralston** [comment]
@chbdetta see above

**Comment by mdipierro** [comment]
Can you cut and paste the error in the console? Cannot see from the video.

**Comment by pdralston** [comment]
```
ERROR:root:Traceback (most recent call last):
  File "D:\My Documents\School Stuff\CSE183\Projects\py4web\py4web\core.py", line 568, in wrapper
    [obj.on_request() for obj in fixtures]
  File "D:\My Documents\School Stuff\CSE183\Projects\py4web\py4web\core.py", line 568, in <listcomp>
    [obj.on_request() for obj in fixtures]
  File "D:\My Documents\School Stuff\CSE183\Projects\py4web\py4web\utils\auth.py", line 80, in on_request
    self.abort_or_redirect("login", "User not logged in")
  File "D:\My Documents\School Stuff\CSE183\Projects\py4web\py4web\utils\auth.py", line 70, in abort_or_redirect
    use_appname=self.auth.use_appname_in_redirects,
  File "D:\My Documents\School Stuff\CSE183\Projects\py4web\py4web\core.py", line 531, in redirect
    raise HTTP(303)
py4web.core.HTTP: 303

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\My Documents\School Stuff\CSE183\Projects\py4web\py4web\core.py", line 609, in wrapper
    ret = func(*func_args, **func_kwargs)
  File "D:\My Documents\School Stuff\CSE183\Projects\py4web\py4web\core.py", line 575, in wrapper
    [obj.on_success() for obj in fixtures]
  File "D:\My Documents\School Stuff\CSE183\Projects\py4web\py4web\core.py", line 575, in <listcomp>
    [obj.on_success() for obj in fixtures]
  File "D:\My Documents\School Stuff\CSE183\Projects\py4web\py4web\core.py", line 280, in on_success
    self.commit()
  File "D:\Users\lv2p8\anaconda3\envs\py4web\lib\site-packages\pydal\base.py", line 708, in commit
    self._adapter.commit()
  File "D:\Users\lv2p8\anaconda3\envs\py4web\lib\site-packages\pydal\adapters\__init__.py", line 55, in wrap
    if args[0].connection:
  File "D:\Users\lv2p8\anaconda3\envs\py4web\lib\site-packages\pydal\connection.py", line 38, in connection
    return getattr(THREAD_LOCAL, self._connection_uname_)
  File "src/gevent/local.py", line 408, in gevent._local.local.__getattribute__
AttributeError: 'gevent._local.local' object has no attribute '_pydal_connection_1876270899784_35536'

127.0.0.1 - - [25/May/2020 15:32:53] "GET /hw6 HTTP/1.1" 200 541
```

**Comment by chbdetta** [comment]
> @chbdetta On reloading the apps, it is not able to be duplicated from the _dashboard because the dashboard is reloading all apps, not just the singular that was changed. It appears that there is some conflict that is raised by only reloading a singular app.

There is also a reload single app button in the dashboard under the routes of an app section. Can you reproduce the behavior by using that?

**Comment by pdralston** [comment]
Reloading the app from _dashboard routes does cause the app to reload properly.

**Comment by chbdetta** [comment]
> Reloading the app from _dashboard routes does cause the app to reload properly.

Is this behavior under unix environment or windows?

**Comment by pdralston** [comment]
This was Windows 10, using Pycharm and Google Chrome with Clear Cache extension

**Comment by pdralston** [comment]
The plot thickens. I launched py4web using WSL and watchgod is working properly there. Pycharm is using the conda environment that I installed for windows. I could direct it to use the one I installed for WSL as a workaround, but this seems like an issue that we would want resolved for windows users.

**Comment by chbdetta** [comment]
The possible cause I can think of is calling Reloader.import from another thread messes up the thread.local resources. This should only happen in windows where the WSGI server is used.

**Comment by pdralston** [comment]
So is there a way for us to detect that the user is running on a windows based environment and change how reloader is called? That seems to be happening properly when ran from the dashboard.

**Comment by chbdetta** [comment]
> ```
> ERROR:root:Traceback (most recent call last):
>   File "D:\My Documents\School Stuff\CSE183\Projects\py4web\py4web\core.py", line 568, in wrapper
>     [obj.on_request() for obj in fixtures]
>   File "D:\My Documents\School Stuff\CSE183\Projects\py4web\py4web\core.py", line 568, in <listcomp>
>     [obj.on_request() for obj in fixtures]
>   File "D:\My Documents\School Stuff\CSE183\Projects\py4web\py4web\utils\auth.py", line 80, in on_request
>     self.abort_or_redirect("login", "User not logged in")
>   File "D:\My Documents\School Stuff\CSE183\Projects\py4web\py4web\utils\auth.py", line 70, in abort_or_redirect
>     use_appname=self.auth.use_appname_in_redirects,
>   File "D:\My Documents\School Stuff\CSE183\Projects\py4web\py4web\core.py", line 531, in redirect
>     raise HTTP(303)
> py4web.core.HTTP: 303
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "D:\My Documents\School Stuff\CSE183\Projects\py4web\py4web\core.py", line 609, in wrapper
>     ret = func(*func_args, **func_kwargs)
>   File "D:\My Documents\School Stuff\CSE183\Projects\py4web\py4web\core.py", line 575, in wrapper
>     [obj.on_success() for obj in fixtures]
>   File "D:\My Documents\School Stuff\CSE183\Projects\py4web\py4web\core.py", line 575, in <listcomp>
>     [obj.on_success() for obj in fixtures]
>   File "D:\My Documents\School Stuff\CSE183\Projects\py4web\py4web\core.py", line 280, in on_success
>     self.commit()
>   File "D:\Users\lv2p8\anaconda3\envs\py4web\lib\site-packages\pydal\base.py", line 708, in commit
>     self._adapter.commit()
>   File "D:\Users\lv2p8\anaconda3\envs\py4web\lib\site-packages\pydal\adapters\__init__.py", line 55, in wrap
>     if args[0].connection:
>   File "D:\Users\lv2p8\anaconda3\envs\py4web\lib\site-packages\pydal\connection.py", line 38, in connection
>     return getattr(THREAD_LOCAL, self._connection_uname_)
>   File "src/gevent/local.py", line 408, in gevent._local.local.__getattribute__
> AttributeError: 'gevent._local.local' object has no attribute '_pydal_connection_1876270899784_35536'
> 
> 127.0.0.1 - - [25/May/2020 15:32:53] "GET /hw6 HTTP/1.1" 200 541
> ```

Can you share the steps to reproduce this error?

**Comment by pdralston** [comment]
The steps I took are in the gif i posted. I literally added a print statement to the controllers in an app and saved the file.

**Comment by pdralston** [comment]
![pycharm_setup_10](https://user-images.githubusercontent.com/25166909/82963387-9f414180-9f77-11ea-8fdc-0be4b1c98cfa.png)

**Comment by pdralston** [comment]
There is my Py4web run configuration

**Comment by chbdetta** [comment]
Does It happen all the time to every app? I don't seem to be able to reproduce it on my windows machine

**Comment by pdralston** [comment]
Yes, every app.

**Comment by pdralston** [comment]
If you would like I can screenshare on zoom or discord

**Comment by chbdetta** [comment]
@pdralston That would be helpful. I can use zoom

**Comment by pdralston** [comment]
Id 94428215953

**Comment by chbdetta** [comment]
@pdralston Do you mind checking your version of pydal? it seems like you are using an old version of pydal. Try to update all your dependencies before debug again. 

```
File "D:\Users\lv2p8\anaconda3\envs\py4web\lib\site-packages\pydal\adapters\__init__.py", line 55, in wrap
    if args[0].connection:
  File "D:\Users\lv2p8\anaconda3\envs\py4web\lib\site-packages\pydal\connection.py", line 38, in connection
    return getattr(THREAD_LOCAL, self._connection_uname_)
  File "src/gevent/local.py", line 408, in gevent._local.local.__getattribute__
```

The code at line 38 in connection.py is changed in this commit: https://github.com/web2py/pydal/commit/2ce2d32699186a1f599dcdb538ed9b9c7c9b43ff#diff-cfd766f4b16b36b986feb807b9fc3997L36-L39

**Comment by pdralston** [comment]
(py4web) D:\My Documents\School Stuff\CSE183\Projects>pip install pydal
Requirement already satisfied: pydal in
d:\users\lv2p8\anaconda3\envs\py4web\lib\site-packages (20190915.2)

How would I update it? See above for what I tried

**Comment by chbdetta** [comment]
cd into the py4web folder and
```
pip install -r requirements.txt
```

**Comment by pdralston** [comment]
That resolved the issue :). Is there not an automatic way to keep the requirements up to date?

**Comment by pdralston** [comment]
I'll update that Piazza post as well

**Comment by chbdetta** [comment]
running
```
pip install -r requirements.txt
```
after each py4web update is the best way to ensure everything works.

**Comment by mdipierro** [comment]
Is this still an issue? I cannot reproduce.

**Comment by mdipierro** [comment]
can this be closed?

**Comment by pdralston** [comment]
Apologies for the delayed response. Issue is resolved and this can be closed.

**Comment by mdipierro** [comment]
Thanks> 👍
