### ISSUE TITLE
Custom form - values not displayed are set to NULL

### ISSUE THREAD

**Issue by jpsteil** [web2py/py4web#241]
Using custom forms, if a field is not displayed on the page the values are being set to null.  Can we change that so they are not changed if they do not exist on the page?

https://groups.google.com/g/py4web/c/6c4njr2SuuQ

**Comment by jpsteil** [comment]
Discussed with Massimo and Tom - it was decided that the best route for now is to set fields to writable=False before calling Form().  This will prevent those fields from being updated.

Leaving ticket open for now for Massismo to review.

**Comment by jpsteil** [comment]
When I posted this question I was sure that web2py handled this case differently.  I was wrong.  I just revisited my web2py code and found that I had specified the list of fields that I wanted editable on the SQLFORM() call.  So, the py4web behavior of updating all the fields is consistent with what I was seeing in web2py.  Sorry for the noise and all the discussion on this yesterday.

Drinks on me next time we're all together!

**Comment by mdipierro** [comment]
Thanks for clarifying. I did not remember correctly myself. But in the end the processing logic should in fact be the same as validate_and_update handled in pydal.

**Comment by mdipierro** [comment]
Can this be closed?

**Comment by qualityliquidfeeds** [comment]
Yes
