### ISSUE TITLE
My expectations for py4web

### ISSUE THREAD

**Issue by WenTao-Love** [web2py/py4web#274]
I hope that py4web can be configured as flexibly and simply as springboot, with strong compatibility and security.
By the way,

Why does py4web have no web2py tool class. For example: MD5, dynamic configuration file Why?
Why ?

Web2py's security and lightweight advantages should be inherited and improved.
Py4web refueling……Come on

**Comment by mdipierro** [comment]
I am not sure I fully understand you.

Yes web2py is more mature but I think, as security they are similar although py4web uses more modern design. 

What is th web2py tool class?
What security feature of web2py is missing in py4web?
md5 should not be used. sha1 is more secure but this is provided by hashlib, not by py4web or web2py.

Anyway. I am listening. Can you be more specific? :-)

Massimo

**Comment by WenTao-Love** [comment]
@mdipierro Thank you for listening!
How to say it? 
In a word, I just hope py4web can surpass web2py, Django and flask! 
At present, I'm just a novice of py4web, and I may have incorrect understanding of it. 
Please forgive me. 
By the way, have you heard about SpringBoot?(https://spring.io/projects/spring-boot/)

**Comment by Kkeller83** [comment]
I think this can be closed no?
