### ISSUE TITLE
py4web not starts

### ISSUE THREAD

**Issue by Narendra-Kumar** [web2py/py4web#28]
Hi,

I try to start py4web on my local machine by following steps as instructed as below: 

**git clone https://github.com/web2py/py4web.git
cd py4web 
python3 -m pip install -r requirements.txt
./py4web-start apps**

But unable to find py4web file after setup. I also try to run Makefile, but fails. I didnot install using through command "**python3 -m pip install py4web**". 
Please provide complete step to make setup.

Regards
Narendra Kumar

**Comment by marlowe240** [comment]
Hi Narendra,

You are right that the py4web-start file is missing so you just need to add it to the py4web directory after cloning the repository.  The py4web-start file should contain the following code.

```
#!/usr/bin/env python3

from py4web.core import main

if __name__ == '__main__':
    main()
```

**Comment by mdipierro** [comment]
I am going to close this because the missing file was added. https://github.com/web2py/py4web/blob/master/py4web-start
