### ISSUE TITLE
No routes displayed using the Dashboard (windows only)

### ISSUE THREAD

**Issue by nicozanf** [web2py/py4web#282]
Using the dashboard, no routes are displayed for any app. No error is present on the console. On Mac the problem is not present.

I've tried to debug the problem: it seems to me that routes are retrieved correctly at first but I was not able to trace their disappearence later...

**Comment by Kkeller83** [comment]
Is this still an issue?

**Comment by nicozanf** [comment]
Yes, it's still an issue with the current py4web version. By the way, it is present also using Tornado.

The headers are visible, but without values:

Rule | Method | Filename | Action | Time(s) | Calls/s | Errors/s
-- | -- | -- | -- | -- | -- | --

**Comment by nicozanf** [comment]
It took me a lot of time, but **I've catched the bug**: 

Reloader.ROUTES is like this in Window:
`[{'action': 'index', 'filename': '_default\\__init__.py', 'method': 'GET', 'rule': ''},.....]}`

and like this in Linux/Mac:

`[{'action': 'index', 'filename': '_default/__init__.py', 'method': 'GET', 'rule': ''},  .....]}`

So, it's a matter of OS path separator ;-)

It can be resolved by modifying line 71 of apps/_dashboard/templates/index.htm :

`              <tr v-for="route in routes" v-if="route.filename.startsWith(selected_app.name+'/')">`


in order to include  || route.filename.startsWith(selected_app.name+'\\')" ...

I'm not totally sure this is the best place to modify it, but I'm making a PR

**Comment by nicozanf** [comment]
Solved by cc86724088b7fd42133faee8b2818b00f6408d47 ;-)
