### ISSUE TITLE
Grid Signature - Use of Params

### ISSUE THREAD

**Issue by jpsteil** [web2py/py4web#296]
I've gone through the current __init__ parameters of the new grid and found three distinct groupings

1.  common parameters that would be set once for the application
2.  database query parameters used in the __init__ method to query the database (to fill grid or the form)
3.  display parameters

Common Parameters
db - the database connection
secret - encryption secret used to encrypt values stored in cookies
token_longevity - how long do we remember saved values
rows_per_page - how many rows are displayed per page
include_action_button_text - include text on buttons or just show icons
search_button_text - text to use on the search button
formstyle - formstyle to be passed to forms that are created by the grid
grid_class_style - grid_class_style to be used on grid displays
mobile_columns - column index of default columns to display when reducing to mobile size

Database Query Parameters
queries - list of queries used to get records to include
fields - fields to display
show_id - include the id in the display
order_by - pydal orderby to use
left - pydal left
requires - dict of 'requires' attributes to apply to specific fields
search_form - FORM to display for search form
storage_values - values to store in storage cookie - form values to remember between displays
storage_key - key to use to identify storage values

Display Parameters
headings - headings to display on grid
create - show New button
details - show Details button
editable - show Edit button
deletable - show Delete button
pre_action_buttons - buttons to include before standard action buttons
post_action_buttons - buttons to include after standard action buttons

The way the grid works today, the __init__ method gathers the grid data or builds the Form.  Therefore, we really can't use the Params class since some of the Common and some of the Database Query parameters are already used before you'd have a chance to modify them.

What I'm proposing is that I no longer build all that stuff in __init__, instead create a new method called generate() that would do all of this creation.  Then I can used the Params class to specify all these params in __init__.  Then at the end of __init__, call generate() if the (new) auto_generate __init__ parm is set to True (will default to True).  But, if you want to override some of the Common or Display Parameters before generating, you can set auto_generate to False, change your params after instantiating Grid and then call generate.  

Obviously, you'd be able to change any of the Display Parameters any time before calling render().

Initially I'd keep most parameters as part of the the __init__ call (maybe leaving out headings, pre_action_buttons and post_action_buttons).  Will also add in a parameter for the new search feature you requested yesterday.
Does this follow your intentions for the use of Params?

Let me know where I'm not meeting your goals.

**Comment by mdipierro** [comment]
Yes. Just one caveat to keep in mind.

When using Auth, we create an Auth object outside any action and we use it inside actions. This means Auth is a fixture and has logic for that.

Form and Grid are not fixtures and I do not think they should be. This means an instance should not be created outside an action and/or used inside multiple actions because there is no guarantee that it is thread safe.

Massimo

**Comment by jpsteil** [comment]
Agreed.  That is why I'm using the GridDefaults outside of an action so I can set it once for the application and pass it to each Grid instance.

I will code up the change outlined above and submit it in a PR for the grid branch.

**Comment by jpsteil** [comment]
I'm still confused on the purpose of the Param() class in the __init__ method vs regular instance variables.  Because I'm missing the bigger picture it seems like I'm adding the self.param = Param() is just giving me a new level of verbosity and adding a new place for instance variables to exist.  

I understand that param will prevent a developer from introducing new instance variables and to ensure that they are using proper variable names.  

I'm guessing it will also be used then to introduce new features (and by extension, new instance variables) without us modifying the class __init__ signature.

If my assumptions are correct, how would you decide whether or not an instance variable should be self.param.xxx or just self.xxx?  I'm guessing I'd still use self.xxx when the instance var is used but the user shouldn't be changing it.

Can you confirm that I'm thinking about this correctly?

**Comment by mdipierro** [comment]
What you say is true but in my mind the major point is this. Without param how does the user know if obj.xxx is an attribute that can safely be changed? The param. prefix does add one level of verbosity by groups together those attributes that are safe to change without breaking internals.

**Comment by jpsteil** [comment]
That works for me.  I agree, it is a good indicator of what they can safely change.  Alternatively, how would you feel about using self._variable_name to indicate this isn't a variable you can change.  Isn't that a python rule of thumb?

To be clear, I'm not disagreeing with you, just trying to make sure I'm understanding the intent and proper usage.

**Comment by mdipierro** [comment]
we could and should use _name for private but there are variables that are not private and still should not be changed

**Comment by jpsteil** [comment]
Got it
