### ISSUE TITLE
Try closed PR for GAE DataStore support

### ISSUE THREAD

**Issue by tomcam** [web2py/py4web#303]
https://github.com/web2py/pydal/pull/624/files

**Comment by nicozanf** [comment]
I think this could be closed because the PR has been merged

**Comment by jparga** [comment]
Is it already fixed?
I have tried and get the same error: 
```
raise ValueError("no %s found for object: %s" % (self.namespace, obj))
ValueError: no dialect found for object: <pydal.adapters.google.GoogleDatastore object at 0x7fa35c5745b0>
```
when I try to use google:datastore as the connector. Although the documentation seems to say thay it is possible to connect Datastaore with py4web.
