### ISSUE TITLE
Grid search_queries - add requires

### ISSUE THREAD

**Issue by jpsteil** [web2py/py4web#310]
I think it would be nice to be able to add a requires to the fields as they are created in the search form. Do you think it would make sense to convert this list of lists to search_query objects or just add another positional value after the query where you you could put a dal requires?

```
search_queries = [search_query('Search by Number', 
                               query=lambda value: db.region.region_number == value, 
                               requires=dal_requires_for_region_number),
                  search_query('Search by id', 
                               query=lambda: db.region.id == value,
                               requires=dal_requires_for_id)
```
or

```
search_queries = [['Search by Number', lambda value: db.region.region_number == value, dal_requires_for_region_number],
                  ['Search by id', lambda value: db.region.id == value, dal_requires_for_region_id]]
```
I think the search_query object would be helpful for developers to see what is available to them as opposed to just knowing the positional arguments available.

Thoughts?

**Comment by mdipierro** [comment]
I would keep the list of lists but maybe expose grid.add_search_query(name,
quey) to add to the list.

**Comment by jpsteil** [comment]
PR submitted
