### ISSUE TITLE
Runtime error 'This event loop is already running' with --watch, Tornado and Win 

### ISSUE THREAD

**Issue by nicozanf** [web2py/py4web#327]
As reported on [this thread](https://groups.google.com/d/msgid/py4web/ae9c4280-80d5-419a-8a15-07fb87f3c160n%40googlegroups.com?utm_medium=email&utm_source=footer), there is this error:

```
    raise RuntimeError('This event loop is already running')
RuntimeError: This event loop is already running
```

running py4web on Windows with Tornado (which is the current default web server) and the --watch command switch, both using lazy and sync values.
Replacing Tornado with gevent resolves the problem.

**Comment by valq7711** [comment]
I found the error:
here we set  `server_config = "windows" `
https://github.com/web2py/py4web/blob/10b4f80e80aeb39fedbc970020f7dcaf2fd67b2f/py4web/core.py#L1234-L1242

but here `server_config == "windows"`  means default wsgi server, not tornado
https://github.com/web2py/py4web/blob/10b4f80e80aeb39fedbc970020f7dcaf2fd67b2f/py4web/core.py#L1206-L1223

also I have not met _dashboard db problems using gevent  20.9
