### ISSUE TITLE
_default app and URL helper

### ISSUE THREAD

**Issue by marlowe240** [web2py/py4web#33]
@actions are correctly routed in the _default app but when I try to use the URL helper to, for example, include an image on a page, the filepath is not being interpreted correctly.

URL('static', 'images/1.jpg') does not behave as expected in the _default app. In other apps, it works as expected.

I haven't been able to figure out the best way to fix this but I believe the solution is related to the following two areas of the core.py file:

365 --> prefix` = '/%s/' % request.app_name if request.app_name != '_default' else '/'`

485 --> path = ('/' if app_name == '_default' else '/%s/' % app_name) + self.path  # the _default app has no prefix``

**Comment by marlowe240** [comment]
I am not sure that this is the ideal way to fix the issue but line 365 of core.py can be written as:

prefix = '/%s/' % request.app_name if request.app_name != '_default' or parts[0]=='static' else '/'

Essentially, if the URL helper is being used to serve content from the 'static' directory, then you need to include the _default prefix in the filepath.

**Comment by mdipierro** [comment]
Not sure I understand the problem. The intended behavior is that if app_name != '_default' URL('static', 'x') == '/' +app_name +'/static/x' but otherwise == '/static/x'
is not doing what intended for you?

**Comment by marlowe240** [comment]
Thanks Massimo, I agree that that is the intended behaviour but if you re-read line 365 in core.py, that is not what it is doing (unless I am missing something). 

I think you need to add something like parts[0]=='static' to the condition to get the intended behaviour.  

Btw, I am really liking all of the changes you've made to py4web!

**Comment by mdipierro** [comment]
I understand the issue now. I think URL generates the correct url /static/filename but the problem is that is not mapped correctly into the static folder of the _default app. I just fixed that in master. Please confirm this works for you and you agree with the solution.

**Comment by marlowe240** [comment]
Perfect! Thank you.
