### ISSUE TITLE
ActionFactory is too magic

### ISSUE THREAD

**Issue by valq7711** [web2py/py4web#333]
These lines of _action_maker makes it impossible to use ActionFactory to build api:
https://github.com/web2py/py4web/blob/60282cd0aa748a4db73e5266847e92d2e6a32624/py4web/utils/factories.py#L51-L52

Also,  I think that this is not fine solution:
https://github.com/web2py/py4web/blob/60282cd0aa748a4db73e5266847e92d2e6a32624/py4web/utils/factories.py#L48-L49
in case of `/user/1` - you will get '1' not 1 - case like this is the source of hard-to-catch bugs

Having a default behavior is fine, but the behavior should be absolutely clear and unambiguous. It should not turn into yet another complex thing with dozen of if/then possible behaviours.

**Comment by mdipierro** [comment]
I do not think these are bugs. ActionFactory is a convenience function. It is not designed to create API. It does not convert URI args.
