### ISSUE TITLE
py4web.com website page: view window too wide

### ISSUE THREAD

**Issue by benlawraus** [web2py/py4web#338]
Hi, The text in the documentation is too far right justified. I cannot see the last words on each line for

http://py4web.com/_documentation/static/index.html#chapter-05

Issue is for

 firefox Developer Edition and Safari on Mac Catalina.

<img width="1080" alt="Screen Shot 2020-11-12 at 5 38 52 AM" src="https://user-images.githubusercontent.com/5177981/98947396-001ef080-24aa-11eb-83a1-f4c27c8fa72e.png">

**Comment by jpsteil** [comment]
An entirely new documentation page is being worked on which will replace this.  I'm not sure of the ETA but I'm hoping we'll see it soon.
