### ISSUE TITLE
Assets folder is missing from source version

### ISSUE THREAD

**Issue by MBfromOK** [web2py/py4web#34]
During source version launch:
assets-folder: D:\Dev\GitHub\py4web\py4web\assets - Does not exist

During pip version launch:
assets-folder: C:\DevSDKs\Python\Python37\lib\site-packages\py4web\assets - Exists

**Comment by mdipierro** [comment]
Try

make assets

**Comment by MBfromOK** [comment]
as in create an empty folder called assets?

**Comment by mdipierro** [comment]
Oh Sorry.  I mean I included a Makefile (https://www.gnu.org/software/make/manual/html_node/Introduction.html) and I typically run

make assets

You can do this in windows but I think you need cygwin

**Comment by mdipierro** [comment]
I am going to close this but please reopen if I the recent commit did not fix the issue for you.
