### ISSUE TITLE
Online documentation is unreadable and doesn't flow to fit the width of the browser

### ISSUE THREAD

**Issue by stodge** [web2py/py4web#340]
Your documentation website doesn't render properly on Chrome or MS Edge unless the browser is resized to thousands of pixels wide. The text doesn't flow if you reduce the width of your browser and there's no horizontal scroll bar. So the documentation is unreadable. Thanks.

**Comment by jpsteil** [comment]
Mike - thanks for reaching out.  Please know that we are in the midst of a transition from this documentation format to a new one.  The current documentation app is being replaced.  Unfortunately I don't have an ETA on when that will be ready.

**Comment by stodge** [comment]
No problem, thanks for letting me know.

**Comment by mdipierro** [comment]
Closing because we are moving to ReadTheDocs
