### ISSUE TITLE
'no such table' in case of `sqlite:memory`

### ISSUE THREAD

**Issue by valq7711** [web2py/py4web#348]
```python
dbm = DAL( 'sqlite:memory')
dbm.define_table( 'my_table'
    Field('name')
)
dbm.commit()
dbm(dbm.my_table).select().first() # - works, no errors

@action('dbm_test')
@action.uses(dbm)
def dbm_test():
    ret = dbm(dbm.my_table).select().first() # error here
    return ret and ret.as_dict()
```
Got `sqlite3.OperationalError: no such table: my_table` when trying request `http://app/dbm_test`
It seems that before the request something kills / closes `dbm` 

PS: below works fine
```python
import sqlite3
conn = sqlite3.connect(':memory:')
c = conn.cursor()
c.execute('''CREATE TABLE my_table(id INTEGER PRIMARY KEY, name text NOT NULL)''')
conn.commit()

@action('dbm_test')
def dbm_test():
    ret = c.execute('SELECT * FROM my_table')
    return dict(ret = ret)

**Comment by valq7711** [comment]
OK, it is pydal issue:
1. sqlite-db in-memory, opened as  just `:memory:`, is only accessible through the connection that was used to open this db. Hence,  the connection should not be thread local (as I understand), no?
2. To be able to have more than one connection to the same in-memory db it should be opened as `"file::memory:?cache=shared"`  but pydal doesn't support such uri.

https://stackoverflow.com/questions/38676691/how-can-i-create-an-in-memory-database-with-sqlite


!!! Also, it seems that  in-memory db **can't be shared between process** altogether
https://stackoverflow.com/questions/15720700/can-two-processes-access-in-memory-memory-sqlite-database-concurrently

**Comment by mdipierro** [comment]
Can you help me test a possible solution?
in file pydal/pydal/adapters/sqlite.py
replace
        if ":memory" in self.uri.split("://", 1)[0]:
            self.dbpath = ":memory:"
with
        if ":memory" in self.uri.split("://", 1)[0]:
            self.dbpath = "file:%s?mode=memory&cache=shared" % uuid.uuid4()

**Comment by valq7711** [comment]
Yes of course!

**Comment by valq7711** [comment]
@mdipierro  your patch works fine!:
```python
#/adapters/sqlite.py
...
import uuid  # required (there is not at the moment)
...

if ":memory" in self.uri.split("://", 1)[0]:
    self.dbpath = "file:%s?mode=memory&cache=shared" % uuid.uuid4()
```

tested on gunicorn with one gevent worker

**Comment by valq7711** [comment]
it needs a warning in the doc that it can only be used for a single-process environment.
The hazard is that it will work but in crazy-random mode

**Comment by Kkeller83** [comment]
I guess this can be closed?

**Comment by valq7711** [comment]
Warning  in doc is required, since there is an example with session in sqlite:memory.

**Comment by mdipierro** [comment]
Can you please add the warning in the docs?

**Comment by mdipierro** [comment]
Than you!
