### ISSUE TITLE
rename models.py and controllers.py on _scaffold

### ISSUE THREAD

**Issue by sugizo** [web2py/py4web#351]
**background**
when application growth sometime dev want to group their similar files into folders (define_table files into models folder, exposed python function to web into controllers folder)
then when define it on __init__.py, an error will occur because there are (models folder and models.py) or (controllers folder and controllers.py)

**suggestion**
better rename models.py and controllers.py into something 
**e.g.** 
models.py = example_models.py
controllers.py = example_controllers.py

thanks

**Comment by valq7711** [comment]
In py4web there is no naming limitation, as it is a regular python program.
You can rename anything.
