### ISSUE TITLE
list:integer in form.py

### ISSUE THREAD

**Issue by jpsteil** [web2py/py4web#357]
list:integer fields don't work

default display in form is []

produces error when comma-separated list of integers is submitted:

ERROR:root:Traceback (most recent call last):
  File "/home/jim/dev/jpsteil/py4web/py4web/core.py", line 737, in wrapper
    ret = func(*func_args, **func_kwargs)
  File "/home/jim/dev/jpsteil/py4web/py4web/core.py", line 697, in wrapper
    ret = func(*args, **kwargs)
  File "apps/routing/__init__.py", line 103, in index
    grid = Grid(path,
  File "/home/jim/dev/jpsteil/py4web/py4web/utils/grid.py", line 359, in __init__
    self.process()
  File "/home/jim/dev/jpsteil/py4web/py4web/utils/grid.py", line 422, in process
    self.form = Form(
  File "/home/jim/dev/jpsteil/py4web/py4web/utils/form.py", line 457, in __init__
    original_value = json.loads(original_value or "[]")
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 1 column 3 (char 2)

**Comment by mdipierro** [comment]
Can you post some code to reproduce?

**Comment by jpsteil** [comment]
Here is an app that shows the issues:


```
#  __init__.py

import os

from pydal.validators import *

from py4web import Session, Cache, Flash, DAL, Field, action, Translator, URL, redirect
from py4web.utils.auth import Auth
from py4web.utils.form import Form, FormStyleBulma


# db settings
APP_FOLDER = os.path.dirname(__file__)
APP_NAME = os.path.split(APP_FOLDER)[-1]

# DB_FOLDER:    Sets the place where migration files will be created
#               and is the store location for SQLite databases
DB_FOLDER = os.path.join(APP_FOLDER, "databases")
if not os.path.exists(DB_FOLDER):
    os.makedirs(DB_FOLDER)

db = DAL(
    "sqlite://int_list.db",
    folder=DB_FOLDER,
    pool_size=1,
    migrate=True,
    fake_migrate=False,
)

cache = Cache(size=1000)

session = Session('askdjfh o2985 yo2n lerk hgoaeng')

#  auth
auth = Auth(session, db, define_tables=False)
auth.use_username = False
auth.param.allowed_actions = ["all"]
auth.param.formstyle = FormStyleBulma
auth.param.login_expiration_time = 60 * 60 * 24 * 30  # expire 30 days
auth.param.password_complexity = {"entropy": 50}
auth.param.block_previous_password_num = 3
auth.define_tables()

auth.enable(uses=(session, db))

db.define_table('test',
                Field('text', required=True,
                      requires=IS_NOT_EMPTY()),
                Field('my_list', type='list:integer'),
                Field('text_list', type='list:string'))

db.commit()


@action('index', method=['GET', 'POST'])
@action.uses(session, db, auth, 'index.html')
def index():
    form = Form(db.test)
    if form.accepted:
        print(form.vars['text'])
        print(form.vars['my_list'])
        redirect(URL('index'))

    return dict(form=form)
```
```
</-- templates/index.html -->

[[=form]]
```
With this you can see the default for display of the field shows [].  When you put items in the list you have to put them inside the brackets, which just isn't very intuitive.

Also, looks like this happens for both integers and strings.  I thought I'd fixed it for strings but evidently not.

-Jim

**Comment by mdipierro** [comment]
Thanks.
