### ISSUE TITLE
Grid How to translate labels(New,Delete, Search,Details, etc)

### ISSUE THREAD

**Issue by isi007** [web2py/py4web#359]
Currently not it possible to translate the labels (new, search, clear, delete,details, etc) in grid.

**Comment by isi007** [comment]
By the way the next elements have not id in html code

<span class="grid-action-button-text">&nbsp;New</span></a>
<input  onclick="document.querySelector('[name=seach_string]').value='';" type="submit" value="Clear">
<input type="submit" value="Search">
<span class="grid-action-button-text">&nbsp;Details</span>
...
...
etc

Because I was thinking in find element by id to do the translate using javascript.

**Comment by jpsteil** [comment]
Massimo - how do you feel about adding params developers could set the New, Details, Edit and Delete buttons?

**Comment by jpsteil** [comment]
I've added id attributes to each button.

new = grid-new-button
details = grid-details-button-_rowid_
edit = grid-edit-button-_rowid_
delete = grid-delete-button-_rowid_

**Comment by jpsteil** [comment]
This was added a while back.  After instantiating the grid, you can set the following in params:

grid.param.new_submit_value - text for submit button on add page 
grid.param.new_action_button_text - text for the 'new' action button in the grid
grid.param.details_submit_value - text for submit button on details page
grid.param.details_action_button_text - text for the 'details' action button in the grid
grid.param.edit_submit_button - text for the submit button on the edit page
grid.param.edit_action_button_text - text for the 'edit' action button in the grid
grid.delete_action_button_text - text for the 'delete' action button in the grid

**Comment by jpsteil** [comment]
This can be closed

**Comment by mkostrikin** [comment]
Tried to use advise from above, but did not work.
With that
```
    grid = Grid(
        path,
       ........
        )
    grid.form.param.submit_value="Works" # This works
    grid.param.new_submit_value="Doesnt" # This does not work 
    return dict(grid=grid)
```
Works page for `/new`, but does not work for grid view.

Please advise

**Comment by mkostrikin** [comment]
> Please advise

```
    grid = Grid(
        path,
       ........
        )
   grid.param.new_submit_value="Works"
   grid.process() # this helps to add above.
   return dict(grid=grid)
```

PS I did not post above for a day. But after I finally found no option and posted, solution appears. LoL

**Comment by mkostrikin** [comment]
> ```
>    grid.process() # this helps to add above.
> ```
grid.process() - gave another bad effect. Collumn with actions buttons - edit, view - become duplicated.
My work-a-round was creating CustomGrid class, where all my string were injected.
