### ISSUE TITLE
_dashboard editor data loss

### ISSUE THREAD

**Issue by jpoutiainen** [web2py/py4web#370]
When editing code via dashboard application in browser it is possible to loose changes in certain conditions.

Windows 10 + brave browser

How to repeat:

1. open dashboard editor
2. select installed app to edit
3. click 'models.py'  (yes just click it so that it opens in the File: accordion)
4. click 'controllers.py', start to edit it in the File accordion. E.g. add 2 spaces somewhere
5. revert changes CTRL + z, click it 3 times.
   when CTRL + z clicked enough many times the editor swaps File accordion contents to models.py contents. Filename is still controllers.py.

6. save mistakenly or automatically --> changes have been lost.

**Comment by mdipierro** [comment]
fascinating. this is a problem with Linux too. ace editor undo is not reset
