### ISSUE TITLE
security access management

### ISSUE THREAD

**Issue by manuelep** [web2py/py4web#375]
Reporting from the [original thread on google  #groups](https://groups.google.com/g/py4web/c/weE2zvgb0dA/m/kYxzmWt1AgAJ):

Is there a way to force each controller that require authentication and the authentication services itself to be served through HTTPS and leave the other controller (that do not require authentication) to be served as requested (HTTP or HTTPS)?

**Comment by mdipierro** [comment]
For security reasons sessions should be shared between http and https and py4web (and web2py) enforce that. That means either we use https everywhere or http everywhere. I do not think this check therefore belongs to py4web.
