### ISSUE TITLE
form.py _action="#" throws a 404

### ISSUE THREAD

**Issue by marlowe240** [web2py/py4web#39]
line 8 of form.py has the following "_action"

form = FORM(_method='POST',_action="#",_enctype='multipart/form-data')

I think the intention here is that the form is supposed to re-call itself but it is throwing me a 404 because it is looking for "app.name/static/#".

I have fixed it by replacing the "#" in _action with a request.url.

form = FORM(_method='POST',_action=request.url,_enctype='multipart/form-data')

I am not sure I fully understand why the "#" is not working on its own but will try to dig into further tomorrow.

**Comment by mdipierro** [comment]
fixed
