### ISSUE TITLE
PyJWT Version 2.0

### ISSUE THREAD

**Issue by DonaldMcC** [web2py/py4web#394]
Seems this has been released 20th Dec and not compatible with py4web - haven't looked at the detail but potentially requirements.txt should be tweaked to reflect this?

**Comment by mdipierro** [comment]
I upgraded to PyJWT-2.0.0-py3-none-any.whl but did not run into any issue. Can you provide more details about the problem?

**Comment by mdipierro** [comment]
Got it. Fixed in #390
