### ISSUE TITLE
Problem displaying records with Upload fields

### ISSUE THREAD

**Issue by rafucisneros** [web2py/py4web#395]
Hello! 

I got a table with a upload field defined as follow:

```
db.define_table('certs_templates',
                Field('name',required=True),
                Field('template', type="upload", required=True),
                )
```

I inserted some records, and then tried to display those records with something like this:

```
form = Form(db.certs_templates, id)
```

but I get the following error:
```
AttributeError: 'Field' object has no attribute 'download_url'
```

![image](https://user-images.githubusercontent.com/32278088/103182864-0d8b1100-4885-11eb-817d-819187df42ca.png)

I'm using py4web pip installation on Windows and python 3.9.1:

py4web==1.20201211.1
pydal==20200910.1

**Comment by agavgavi** [comment]
Upload fields need a URL to be used for where to download the file from in edit forms. So there should be a `uploadfolder=YOUR_PATH` within your upload field. 

Mine for example is stored just within `UPLOAD_FOLDER = os.path.join(APP_FOLDER, "uploads")` in `settings.py` and my model would be:

```
db.define_table('certs_templates',
                Field('name',required=True),
                Field('template', type="upload", required=True, uploadfolder=UPLOAD_FOLDER),
                )
```

**Comment by rafucisneros** [comment]
Hi! Thanks for the answer.

I don't think that's the problem, as the files are being correctly uploaded to the default folder "uploads".
Anyway I tried to change the folder to a custom one, but the problem persists.

**Comment by mdipierro** [comment]
You common.py should contain the following code (if not, get the latest):

```
# #######################################################
# Define a convenience action to allow users to download
# files uploaded and reference by Field(type='upload')
# #######################################################
if settings.UPLOAD_FOLDER:
    @action('download/<filename>')                                                   
    @action.uses(db)                                                                                           
    def download(filename):
        return downloader(db, settings.UPLOAD_FOLDER, filename) 
    # To take advtange of this in Form(s)
    # for every field of type upload you MUST specify:
    #
    # field.upload_path = settings.UPLOAD_FOLDER
    # field.download_url = lambda filename: URL('download/%s' % filename)
```

The last line indicates you have to tell your field how to download the uploaded file:

```
db.certs_templates.demplate.download_url = lambda filename: URL('download/%s' % filename)
```

Does that work?

In web2py there is one default download function. In py4web the download action is defined in common.py but fields require explicit knowledge of its path in case you choose to have a different url path.

**Comment by rafucisneros** [comment]
it works! Thanks so much!
