### ISSUE TITLE
Grid: show_id parameter is not working

### ISSUE THREAD

**Issue by rafucisneros** [web2py/py4web#396]
Hi, I've got some problems trying to show ids in the grids. I added show_id=True parameter and added db.table.id to fields parameter, but it is still not showing.

I took a look at grid.py code (line 302 at grid branch)
```
key_is_missing = False
for field in self.param.fields:
    if field.table._tablename == pt._tablename and field.name == pt._id:
        key_is_missing = True
if key_is_missing:
    #  primary key wasn't included, add it and set show_id to False so it doesn't display
    self.param.fields.append(pt._id)
    self.param.show_id = False
```

I believe logic should be reverse here: key_is_missing starting at True and if it is found in self.param.fields, then set key_is_missing as False. 

Also there is something weird with the condition there, as it is being evaluated always as True (I get an error trying to print(field.table._tablename == pt._tablename and field.name == pt._id), but puttig prints after that always gets printed). By printing field.name and pt._id I found out that field.name is id, but pt._id is table.id, so to right would be to compare with pt._id.name

I changed the code to this and it works fine:
```
key_is_missing = True
for field in self.param.fields:
    if field.table._tablename == pt._tablename and field.name == pt._id.name:
        key_is_missing = False
if key_is_missing:
    #  primary key wasn't included, add it and set show_id to False so it doesn't display
    self.param.fields.append(pt._id)
    self.param.show_id = False
```

**Comment by rafucisneros** [comment]
I created a pull request for this. I'm dubious if do the fix in "Grid" or "Master" branch.

**Comment by jpsteil** [comment]
The grid branch is really outdated.  I believe all of this has already been fixed in the master branch.

Can you confirm that it is working in master?

**Comment by rafucisneros** [comment]
It is indeed fixed at master branch. However it is not available at version installed using pip.

Thanks!

**Comment by mdipierro** [comment]
Will deploy a new version asap.
