### ISSUE TITLE
CLI new_app args

### ISSUE THREAD

**Issue by paolopas** [web2py/py4web#398]
How could do click guess that APPS_FOLDER is missing?

 ```
$ ./py4web.py new_app -h
Usage: py4web.py new_app [OPTIONS] [APPS_FOLDER] APP_NAME
...
$ ./py4web.py new_app superheroes
Usage: py4web.py new_app [OPTIONS] [APPS_FOLDER] APP_NAME
Try 'py4web.py new_app -h' for help.

Error: Missing argument 'APP_NAME'.
```

Maybe **new_app** should do like the **call** command, that is make APPS_FOLDER mandatory,
OR defaulted arguments like APPS_FOLDER should better go in OPTIONS

**Comment by mdipierro** [comment]
Yes app_folder should always be mandatory

**Comment by paolopas** [comment]
I think the second option was the most elegant (and clean) solution, is this your last word?
Or maybe we need a coin?
