### ISSUE TITLE
Mission and Vision of web3py

### ISSUE THREAD

**Issue by JusticeN** [web2py/py4web#4]
Hello,
i take a look at your code for web3py and i am pretty impressed of the new direction you want to take with this library.

i would like to invest some time for contribution but first of all, it is possible to clarify the vision of the project? i mean answering questions like what do we want to achieve or to do better than web2py?

i have many open questions like:

1. How does the new architecture will look like?
2. which standard modules have to be implemented? for example kind of SQLHTML using wue in Background, ....
3. does web3py will also be backward compatible ? to all futures versions ?

here are some ideas but we need to define the vision before choosing to implement it:

- i am a fan of microservices. will each apps be a kind of microservices ? if yes we can implement usecases like auth login, register, reset_password and so on ...  as separated apps and create a kind of service binding who will fetch data from different service.

- apps library as a Github repo with a possibility to install different apps just by running a command like: `python3 web3py.py install http://.....app_name.git [tag, version]` so it will be easier to develop custom apps that can be used for known cases. like cms, crm, erp, .... . this will help many users run web3py and easilly install needed apps like wordpress or joomla does.

- admin app for creating small customizable application. an apps can just contains a python and html file. or maybe just a python file if someone need to buid micro api to connect to external services. this may be easier to implement in an online editor like in web2py.

- global configurable routes with staging and prod environement. make it possible to install app. and then test it in a staging system only available on localhost or in a staging url Path. and with just on click in the admin app or as command, to make it available as usual in `/app/...` (as prod). so it will be easier to manage production apps

- or some people will prefer to have different instance for each environement(1 server for staging, 1 for dev, 1 for prod, ...). in this case a command like `python3 web3py.py deploy app_name --env [staging, prod, ...]`. (or as action in the admin app.)
[env] can literally be configured in an .ini file like this `env_name       IP:Port`. this can be implemented through different channels like ssh/ftp, rsync, SCM(git, svn, ...) or even with an  internal RESTAPI connection. which will allow 2 web3py instance to communicate. (may be this can also be used to auto sync session :-) )

my motivation is to build a library which will be easier for small to big businesses to use and manage their data. example: download a zip, unzip it no installation needed like web2py, install some app for your usecase, test it love it or change it easily, push it to your production server, enjoy and focus on your business. 

what do you think about this ?

**Comment by JusticeN** [comment]
we can also differentiate modules(may be just one python file defining some tables and exposing REST api for CRUD operation, bottle can do it very well) and applications(special usecases which use some modules diffined in a manifest file or custom variables that will be read from web3py).

here are some example of micro-application(modules) that can just be intalled if needed.
- auth_basic
- auth_oauth_* #[facebook, twiter, ...]
- auth_cas_server
- auth_cas_client
- crm_contacts
- crm_products
....

so with this standard modules i can create application like my custom CRM who just use use module i need depending of the type of business i have.

**Comment by mdipierro** [comment]
> On Mar 28, 2019, at 9:28 AM, JusticeN <notifications@github.com> wrote:
> 
> Hello,
> i take a look at your code for web3py and i am pretty impressed of the new direction you want to take with this library.
> 
> i would like to invest some time for contribution but first of all, it is possible to clarify the vision of the project? i mean answering questions like what do we want to achieve or to do better than web2py?
> 
> i have many open questions like:
> 
> How does the new architecture will look like?
I like your ideas. A minimalist core and more contrib modules.
> which standard modules have to be implemented? for example kind of SQLHTML using wue in Background, ….
we need a way to report exceptions and generate/process forms. we need authentication and authorization. The rest is optional.
> does web3py will also be backward compatible ? to all futures versions ?
The core yes. The contrib modules no. The smaller the core, the easier will be to maintain.

> here are some ideas but we need to define the vision before choosing to implement it:
> 
> i am a fan of microservices. will each apps be a kind of microservices ? if yes we can implement usecases like auth login, register, reset_password and so on ... as separated apps and create a kind of service binding who will fetch data from different service.
> 
I like microservices too.
> 
> apps library as a Github repo with a possibility to install different apps just by running a command like: python3 web3py.py install http://.....app_name.git [tag, version] so it will be easier to develop custom apps that can be used for known cases. like cms, crm, erp, .... . this will help many users run web3py and easilly install needed apps like wordpress or joomla does.
> 
yes. this will be part of the dashboard app, not the core. work in progress.
> 
> admin app for creating small customizable application. an apps can just contains a python and html file. or maybe just a python file if someone need to buid micro api to connect to external services. this may be easier to implement in an online editor like in web2py.
> 
can have multiple scaffolding apps on github. 
> global configurable routes with staging and prod environement. make it possible to install app. and then test it in a staging system only available on localhost or in a staging url Path. and with just on click in the admin app or as command, to make it available as usual in /app/... (as prod). so it will be easier to manage production apps
> 
I want to move away from global routes. apps can use @action(path) and path can be ‘/$APP/default/index/<id>’ using the bottle syntax + $APP. it is simple and powerful.
> 
> or some people will prefer to have different instance for each environement(1 server for staging, 1 for dev, 1 for prod, ...). in this case a command like python3 web3py.py deploy app_name --env [staging, prod, ...]. (or as action in the admin app.)
> [env] can literally be configured in an .ini file like this env_name IP:Port. this can be implemented through different channels like ssh/ftp, rsync, SCM(git, svn, ...) or even with an internal RESTAPI connection. which will allow 2 web3py instance to communicate. (may be this can also be used to auto sync session :-) )
> 
I would go with 

python web2py {folder} — {args}

the app in {folder}/__init__py will find the args in sys.args. The rest should be left to the app.
> 
> my motivation is to build a library which will be easier for small to big businesses to use and manage their data. example: download a zip, unzip it no installation needed like web2py, install some app for your usecase, test it love it or change it easily, push it to your production server, enjoy and focus on your business.
> 
I am very interested in IOT apps and making this easy to run in embedded devices.
> what do you think about this ?
> 
I think we are very much on the same page

**Comment by tyoc213** [comment]
By the way web3py is already taked from readthedocs

**Comment by kenseii** [comment]
Maybe we can have jwt as one of the defaults auth method(not in contrib) instead of encouraging basic_auth as maybe it is safer and some microservices projects are using flask-jwt for the auth between services.
