### ISSUE TITLE
Shouldn't utils.tags belongs to pydal instead to py4web?

### ISSUE THREAD

**Issue by mbelletti** [web2py/py4web#400]
It seems that could be useful also to pydal "only" users.

**Comment by mdipierro** [comment]
Good point. Let's discuss this on the mailing list.

**Comment by mdipierro** [comment]
I agree with this. I will move it. this will break apps.

**Comment by mbelletti** [comment]
Closed by 35977858a2618d85b65bd610d23217fde5f5dd3d
