### ISSUE TITLE
Upload Fields and PR #379

### ISSUE THREAD

**Issue by agavgavi** [web2py/py4web#411]
_Copied from the py4web group for extra visibility linked [here](https://groups.google.com/g/py4web/c/5hl6YEANUmI)_

Good afternoon,

I've been working with an application that deals with file uploads through the Form class. After PR #379's change, uploads will no longer occur in my program due to the upload field not showing up in bottle's request.forms.

By doing ` if not field.name in post_vars: continue` since upload fields aren't stored in the request.forms FormDict object and instead [stored in request.files](https://bottlepy.org/docs/dev/tutorial.html#file-uploads), py4web doesn't know how to handle file uploads.

Am I doing something wrong? My field is defined as:
```python
Field(
       "upload_file",
        "upload",
        label=T("Dataset Upload (CSV)"),
        uploadfolder=UPLOAD_FOLDER,
    )
```

and before I could just access the filename through `form.vars['upload_file']`, but now the entire processing loop is skipped for upload fields in the Form class, so it will never appear.

Thank you for any suggestions anyone has on fixing this, for now I've just commented out the if statement that was added in the PR and things return to how it was before.

**Comment by valq7711** [comment]
I think `request.forms` should be replaced with `request.POST`. Can you try/test?

**Comment by valq7711** [comment]
`request.POST = request.forms + request.files`
that's the only difference

**Comment by agavgavi** [comment]
Worked perfectly, thanks for the info, I can make a PR or you can if you want.

**Comment by valq7711** [comment]
it's better if you do it ;)

сб, 16 янв. 2021 г. в 02:44, Andrew Gavgavian <notifications@github.com>:

**Comment by agavgavi** [comment]
Very true, I've fallen back from being in the top 5 contributors last spring, got to up my game to be back in the leagues of the big shots like you guys, haha :P

**Comment by Kkeller83** [comment]
Is this a pr for the py4web Form.py or how is it related?

You seem to be using bottle specific Form classes with pydal no?

Anyhow maybe you guys can elaborate a bit more what's going on here please?

Thanks!

**Comment by valq7711** [comment]
@Kkeller83 
bottle `request.forms` and `request.files` are just derived properties from `request.POST` (they are just result of filtering of `request.POST` and nothing else)
Using `request.forms` in `form.py` forces you to hold file upload yourself (by request.files) like in this example
https://groups.google.com/g/py4web/c/2ZYc5yHMgDQ

This condition is always `False` as there are no files in `request.forms` by design
https://github.com/web2py/py4web/blob/411d80f580b837f6bebcc42f318ec4cb5e3c796b/py4web/utils/form.py#L474

**Comment by valq7711** [comment]
And yes, I think it should work with pydal smoothly like in web2py
https://github.com/web2py/py4web/blob/411d80f580b837f6bebcc42f318ec4cb5e3c796b/py4web/utils/form.py#L494-L496
