### ISSUE TITLE
Grid Primary Table

### ISSUE THREAD

**Issue by rafucisneros** [web2py/py4web#412]
Hi. I ran into a situation using grid where I had 2 tables, and using post_action_buttons with append_id=True I was getting the id of the wrong table.

Looking at the code I arrived here (grid.py, line 382):
``` 
      self.action = parts[0] or "select"
      self.tablename = self.get_tablenames(self.param.query)[0]  # what if there ar 2?
      self.record_id = safe_int(parts[1] if len(parts) > 1 else None, default=None)
```

which doesn't seem clear how to set the primary table of the grid. Is there any known way or trick to set the primary table of the grid? In my case I was using the following query, and getting the id from db.sections when I wanted id from db.certs:

```
        query = (
              (db.certs.id != None)
            & (db.certs.signed_by_professor == False)
            & (db.sections.id == db.certs.section)
            & (db.sections.instructor == user)
            )
```

I modified the code, added a new parameter to grid to set primary table:

```
        if(self.param.primary_table):
            self.tablename = self.param.primary_table 
        else:
            self.tablename = self.get_tablenames(self.param.query)[0]  # what if there ar 2?
```

That solved my situation. I can make a pull request with this code if you like.

**Comment by jpsteil** [comment]
The tablename is calculated using the first table it finds in the list of tables for the query or left join.  In your example which tablename is it getting and which tablename do you want it to get?

**Comment by rafucisneros** [comment]
It was getting "sections" table, but I want it to get "certs" table.

This is the query I used:
```
query = (
              (db.certs.id != None)
            & (db.certs.signed_by_professor == False)
            & (db.sections.id == db.certs.section)
            & (db.sections.instructor == user)
            )
```
and the left join:
```
        left=[
            db.auth_user.on(db.certs.user == db.auth_user.id),
            db.users_info.on(db.certs.user == db.users_info.user_id),
            db.sections.on(db.certs.section == db.sections.id),
            db.events.on(db.sections.event == db.events.id)
        ],
```

**Comment by jpsteil** [comment]
does it behave differently if you list (db.sections.instructor == user) as the 'first' query?  I agree this needs to be fixed, probably the way you have suggested. 

Massimo - do you feel this warrants an update to the grid signature, or should we handle it with param as suggested above? Or, do you have other thoughts on this?

**Comment by rafucisneros** [comment]
Nope, it behaves the same. Actually I added "(db.certs.id != None)" trying to make "certs" the primary table., but it didn't work.

**Comment by jpsteil** [comment]
Submitting PR - this can be closed.
