### ISSUE TITLE
prerequisites fixtures can't have their own prerequisites?

### ISSUE THREAD

**Issue by valq7711** [web2py/py4web#427]
@mdipierro 
It seems that prerequisites fixtures can't have their own prerequisites - is that by design?

https://github.com/web2py/py4web/blob/e9813fccf9f1be249f0a1c15f5a3ad929acf2d70/py4web/core.py#L705-L720

**Comment by mdipierro** [comment]
Yes. the while loop is recursive. :-)
if you find it does not work as intended, please post an example and reopen this ticket.

**Comment by valq7711** [comment]
Oh yeah, `stack.extend` I was blind;)
