### ISSUE TITLE
Error in 'examples' app using Vue.js Bulma

### ISSUE THREAD

**Issue by woodyl** [web2py/py4web#433]
I'm getting this error:

```
File "/.../py4web/lib/python3.9/site-packages/py4web/utils/url_signer.py", line 116, in sign
    return jwt.encode(payload, key, algorithm="HS256").decode("utf-8")
AttributeError: 'str' object has no attribute 'decode'")
```

when I try any of the Bulma/Vue.js options in the 'examples' app. I think it is related to this:

https://github.com/SimpleJWT/django-rest-framework-simplejwt/issues/326

**Comment by Kkeller83** [comment]
I think this was fixed. Could you check?

**Comment by woodyl** [comment]
> I think this was fixed. Could you check?

Yes, looks good now.
