### ISSUE TITLE
Obtain route specific auth.enable() RESTful API Model

### ISSUE THREAD

**Issue by macneiln** [web2py/py4web#445]
How do I get the model for a given RESTful Auth Route API exposed by auth.enable() so that I can build my form client-side before submitting via Axios?

Looking through py4web/auth.py I don't seem to see this as an option other than potentially the "config" auth route but that doesn't really expose the current form field details for each specific route, i.e. login, register, etc. so I'm unsure of it's function.

It would be great if it could function similarly to the PyDAL RESTful API or if there is an existing method please let me know as I don't see anything about this in the documentation either.

*********************
**Chapter 11 Documentation:**
![image](https://user-images.githubusercontent.com/6424306/107474165-be9bff80-6bd6-11eb-9c78-7a7e6cbcc021.png)
*********************
**Chapter 06 Documentation:**
![image](https://user-images.githubusercontent.com/6424306/107474348-10dd2080-6bd7-11eb-980f-6c105e79a4de.png)
*********************

**Comment by mdipierro** [comment]
Sorry do not fully understand. Can you clarify?

**Comment by macneiln** [comment]
Hi Massimo,

I'm hoping that something can be built (if not already existing) for the auth api routes to get the form structure for each route dynamically so the form can be built client side instead of hard coding the form fields in an auth client view. I'm hoping it would work similar (or identical) to the "?@model=true" feature of the RESTful DAL API.

This would return an array of fields with all their attributes, i.e. name, default value, label, type, if the field is readable/writeable, options, regex to satisfy the form field client side, etc. (image above in prior post).

Example:
- Currently to use the **auth/api/login** API you would need to know the form required a user name and password field, whereas I would like to call something like **auth/api/login?@model=true** and have it return the form fields and their attributes so I can dynamically built the form for the user client side. Same with all the auth/api routes such as the **auth/api/register?@model=true**, **auth/api/profile?@model=true**, etc.

That way, it's more generic and flexible if additional fields are added/removed from the auth pages. For example if a decision was made to require address information when registering, the generic client side auth view would not need to be manually updated as these new form fields would be automatically built as long as they are returned from the @model=true view.

**Comment by mdipierro** [comment]
This was done. Thank you!
