### ISSUE TITLE
Is there an ETA for a stable release/ release candidate?

### ISSUE THREAD

**Issue by DMunkei** [web2py/py4web#450]
Been using web2py, if this project is coming to an end/production stable build in the near future or if some sort of ETA is set somewhere to migrate to this from web2py.

**Comment by jpsteil** [comment]
I don't have a date for when it will be 'released', but I feel it is very stable.  I would definitely start working on a migration plan.  Best thing to do would be to read through the docs (help identify places that need work) and post questions to the google group.  I'm happy to answer any questions to help you get started.  The speed improvements are worth it.

**Comment by rnjv** [comment]
Is py4web still active or getting a RC soon?

**Comment by mdipierro** [comment]
At this point I consider py4web stable.
