### ISSUE TITLE
Auth API Endpoints Defunct

### ISSUE THREAD

**Issue by Kkeller83** [web2py/py4web#469]
Only the login endpoint of the auth api works. The other endpoints return: 404:

{appname}/auth/api/register (POST)

{appname}/auth/api/login (POST)

{appname}/auth/api/request_reset_password (POST)

{appname}/auth/api/reset_password (POST)

{appname}/auth/api/verify_email (GET, POST)

{appname}/auth/api/logout (GET, POST) (+)

{appname}/auth/api/profile (GET, POST) (+)

{appname}/auth/api/change_password (POST) (+)

{appname}/auth/api/change_email (POST) (+)

From Chapter 11: 

http://py4web.com/_documentation/static/en/chapter-11.html

**Comment by mdipierro** [comment]
I cannot reproduce the problem. Also the referenced chapter 11 is not about auth. I suspect this problem was fixed some time ago.
Does the tests/test_auth.py pass for you? It tests the Auth API

**Comment by Kkeller83** [comment]
Here is what I get when trying to register a user with a fresh
scaffofed app:  (404) with postman

[image: image.png]

Am Sa., 17. Apr. 2021 um 22:35 Uhr schrieb mdipierro <
***@***.***>:

**Comment by Kkeller83** [comment]
Was my bad not using postman the right way. All good
