### ISSUE TITLE
Reloader bug  

### ISSUE THREAD

**Issue by valq7711** [web2py/py4web#48]
Reloader reloads foreign modules (from other apps) if application names start with the same letters. It makes a terrible mess in action/routes/sessions. I tore a lot of my hair out to catch this      

https://github.com/web2py/py4web/blob/84ff16bf2fc2c82a6755e7013a0aefa357564933/py4web/core.py#L681

![reloader_bug](https://user-images.githubusercontent.com/11394363/65281414-40e7d780-db3b-11e9-965d-be966d5c90c1.png)

**Comment by mdipierro** [comment]
Thanks for the fix.
