### ISSUE TITLE
The Search feature does not work on the Documentation site

### ISSUE THREAD

**Issue by nicozanf** [web2py/py4web#490]
The documentation site on https://py4web.com/_documentation/ has been updated following Issue #479.

Unfortunately, the Search feature does not work anymore. Inspecting the page, you can see the error: "Uncaught ReferenceError: Stemmer is not defined", which should be resolved by upgrading the versions of sphinx / sphinx_rtd_theme followed by a new generation of the docs.

**Comment by Kkeller83** [comment]
Is this still an issue Nico?

**Comment by nicozanf** [comment]
Yes, unfortunately it's still an issue ;-(

If you [search for something](https://py4web.com/_documentation/static/en/search.html?q=something&check_keywords=yes&area=default#) it remains "Searching..." forever. The [same search](https://nicozanf.github.io/py4web-doc/en/master/search.html?q=something&check_keywords=yes&area=default#) takes less than one second on my repository or if you copy all the properly generated files locally.

**Comment by nicozanf** [comment]
It works now!
