### ISSUE TITLE
The URL helper is not documented anywyere

### ISSUE THREAD

**Issue by lucadealfaro** [web2py/py4web#491]
and same for the URLsigner.  This bug is created to keep track of the problem.  Massimo if you tell me where to add it I will be happy to add documentation.

**Comment by nicozanf** [comment]
Hi Luca,
I've already added the URLsigner documentation few weeks ago. It's on the Fixture chapter:  https://py4web.com/_documentation/static/en/chapter-06.html#the-urlsigner-fixture (obviously every improvement is highly appreciated!).
About the URL helper, I've found only this reference: https://py4web.com/_documentation/static/en/chapter-10.html#url .

BTW: the Search function is currently broken with the official manual - I've already opened an issue. For the moment you could use my site on https://nicozanf.github.io/py4web-doc/
