### ISSUE TITLE
Binaries are out of synch with new py4web

### ISSUE THREAD

**Issue by lucadealfaro** [web2py/py4web#492]
The binaries for Windows are out of synch with the new py4web, and in particular, in core.py, required_folder is missing. 
So apps built against the new py4web cannot run against those binaries. 
One should either update the binaries, or else, remove them from the installation instructions.

**Comment by valq7711** [comment]
Just in case: 
As windows user Im happy with this https://winpython.github.io/

( does not require admin,   does not require system-wide installation)

**Comment by lucadealfaro** [comment]
Sure.  I am mentioning this because some students in my class tried installing the binaries, and the apps I am distributing don't work because of incompatible (old) py4web.

**Comment by nicozanf** [comment]
Hi, I've just updated the binaries on my site with the latest py4web version, with Python 3.8.6 and PyInstaller 4.2. There should be no problem now ;-)
