### ISSUE TITLE
no decode needed for jwt? 

### ISSUE THREAD

**Issue by sp1d3rx** [web2py/py4web#493]
I accessed the http://127.0.0.1:8000/myfeed on a windows pc, currently running in VSCode on Py 3.7. It gives me an error:

  ```
  return (URL(path), jwt.encode(data, Session.SECRET).decode())
AttributeError: 'str' object has no attribute 'decode'
py4web\utils\factories.py:81

ERROR:tornado.access:500 GET /myfeed (127.0.0.1) 143.34ms
```
I removed the ".decode()" and that fixed the error and now I can access "/myfeed".
jwt.encode apparently returns a str, and not a bytes, as the comments would have me believe.

**Comment by sp1d3rx** [comment]
The signature for jwt.encode is this:

    def encode(
        self,
        payload: Dict[str, Any],
        key: str,
        algorithm: str = "HS256",
        headers: Optional[Dict] = None,
        json_encoder: Optional[Type[json.JSONEncoder]] = None,
    ) -> str:

**Comment by mdipierro** [comment]
fixed
