### ISSUE TITLE
Field Uploads are broken 

### ISSUE THREAD

**Issue by Kkeller83** [web2py/py4web#498]
Since commit (validate image fields before upload) images can not be uploaded anymore. 
Line 479 in forms.py adds upload files to a list, but the files are written to the disk as 0 bytes.

The previous code that worked was: 

478                                     if field.uploadfolder:                  
479                                         value = field.store(
480                                             value.file, value.filename, fiel
481                                         )

**Comment by agavgavi** [comment]
I'll look into this, the reason for the pr was that any validation of the upload fields that failed would still cause the file to be saved. So even if the file is of the wrong type it will still be stored on the server. I'm not sure what may be going wrong with it, you were testing based on my blog app right?

I'll test with that tomorrow.

**Comment by Kkeller83** [comment]
I tried to fix it for a good 1,5 hours but could not get anywhere. Could you check soon when you have a moment? Otherwise file uploads are just broken at the moment. 

if field.type == "upload":
                                value = request.files.get(field.name)
                                delete = post_vars.get("_delete_" + field.name)
                                if value is not None:
                                    if field.uploadfolder:
                                        uploaded_files.append(tuple(field, value))
                                elif self.record and not delete:
                                    value = self.record.get(field.name)
                                else:
                                    value = None
                            elif field.type == "boolean":
                                value = value is not None
                            if value is not None:
                                validated_vars[field.name] = value
                            if error:
                                self.errors[field.name] = error
                    self.vars.update(validated_vars)
                    if validation:
                        validation(self)
                    if self.record and dbio:
                        self.vars["id"] = self.record.id
                    if not self.errors:
                        for file in uploaded_files:
                            field, value = file
                            value = field.store(
                                value.file, value.filename, field.uploadfolder
                            )

**Comment by agavgavi** [comment]
Before I make the PR to fix it, try this:
Update: `uploaded_files.append(tuple(field, value))` to `uploaded_files.append(tuple((field, value)))`.
Then add `self.vars.update(validated_vars)` right under `self.accepted = True` outside of the `for files in uploaded_files` loop:

```python
if not self.errors:
  for file in uploaded_files:
      field, value = file
      value = field.store(
          value.file, value.filename, field.uploadfolder
      )
      if value is not None:
          validated_vars[field.name] = value
  self.accepted = True
  self.vars.update(validated_vars)
  if dbio:
      self.update_or_insert(validated_vars)
```

**Comment by Kkeller83** [comment]
I did not work :(

[image: image.png]

Here is the test app I am using (based on your code from the blog app):

You can download it and unzip in apps:

https://drive.google.com/file/d/154UyrLmIBOcy_c-sHQh2DP2EFMtmkXws/view?usp=sharing



Am Mo., 19. Apr. 2021 um 19:28 Uhr schrieb Andrew Gavgavian <
***@***.***>:

**Comment by agavgavi** [comment]
Looking at your code, I don't see anywhere that the profile model is instantiated, so I can't test your app. When I create an account and then try to edit my profile I can't do anything because the profile table doesn't have me in it.

Is this by design? Am I supposed to add myself in the dashboard?

**Comment by agavgavi** [comment]
Once I made a profile record for myself in the dashboard, everything works for me, can you describe what the issue is?

**Comment by Kkeller83** [comment]
Yeah you need to at yourself via the dashboard in the app as you would need
a custom registration form due to the profile and Auth_user table being
linked and the image field of the profile table is not exposed in the
standard sign up Form.

I will create a custom sign up form at some point.

Issue appear when you try to upload a picture in your profile.

Upload works but the picture is always blank.

**Comment by agavgavi** [comment]
![image](https://user-images.githubusercontent.com/17018800/115297135-b26d7a80-a110-11eb-9e43-369a0880ded2.png)
As seen above, when uploading an image it works fine, I did not adjust your code at all and only added myself through the dashboard.

Have you restarted py4web since adjusting the code in Form.py? Watcher will not see changes in the py4web code only in the apps folder, so you need to restart your py4web after you've updated Form.py.

**Comment by Kkeller83** [comment]
That is really odd.

I did save form.py and restart py4web completely.

Several times just now.

For me, when I upload a new pictures .. actually 2 pics get created.
One with 0 byes (which is the one displayed) and a second one with a
similar name which is the actual new uploaded image, but that is not the
one in the database.
Seems like during the iteration the loop thinks there are 2 pics
uploaded_files?

I also see this output in the terminal:

[image: image.png]


Am Mo., 19. Apr. 2021 um 22:13 Uhr schrieb Andrew Gavgavian <
***@***.***>:

**Comment by Kkeller83** [comment]
Also "check to remove" pic does not work for me.



Am Mo., 19. Apr. 2021 um 22:35 Uhr schrieb Kevin Keller ***@***.***

**Comment by agavgavi** [comment]
Yes, check to remove doesn't work since you have commented out the part that will remove it. Since this model is based off a list comprehension instead of and actual database table, you need to do all of io yourself and update/remove the file yourself. So by un-commenting:

```python
if update_icon != profile.image:
  # If the new icon (which can be default.jpg) isn't the same icon as before, remove the old one and update
  if profile.image != "default.jpg":
      cleanup_image(profile.image)
      resize_image(update_icon)
  profile.update_record(image=update_icon)
```
(This if statement should be at the same level as `if aform.vars["image"]:`)


I can't see the terminal output that you posted, all I see is :`[image: image.png]` without any actually displaying image.

**Comment by Kkeller83** [comment]
Ah nice.

Let me re-implent check to remove.

And this works for me now (skipping the first element in the loop)

for file in uploaded_files[1:]:

                            field, value = file

                            field.store(

                               value.file, value.filename,
field.uploadfolder

                            )

                            if value is not None

Am Mo., 19. Apr. 2021 um 22:50 Uhr schrieb Andrew Gavgavian <
***@***.***>:

**Comment by Kkeller83** [comment]
Indeed, check to remove works now again.

And upload also works now with your updated code plus the skipping part...

Should I create a PR for that?



Am Mo., 19. Apr. 2021 um 22:56 Uhr schrieb Kevin Keller ***@***.***

**Comment by Kkeller83** [comment]
Here is my full py4web environment including the currently working forms.py
and my code untouched apart from the "check to delete" uncommenting.

https://drive.google.com/file/d/1B0pTDYOX44YXSU--OESGzj_kuozEB5lH/view?usp=sharing



Am Mo., 19. Apr. 2021 um 22:59 Uhr schrieb Kevin Keller ***@***.***

**Comment by agavgavi** [comment]
This is odd because with the code I mentioned before I don't get duplicate file uploads at all, and skipping the first will cause it to break on mine. I don't see why yours works with skipping the first while mine doesnt.

**Comment by agavgavi** [comment]
Okay, I have solved the issue, somehow you lost the return value for `field.store`. 
You have:
```py4web
field.store(
    value.file, value.filename, field.uploadfolder
)
```
The current version of the code in the github has this, which is what you are missing.
```py4web
value = field.store(
    value.file, value.filename, field.uploadfolder
)
```

**Comment by Kkeller83** [comment]
Looks like I introduced a bug while trying to fix one.. a meta bug :).

Thanks for fixing this Drew.

In the end, we do not a PR though for those 2 lines:
(added parentheses)

uploaded_files.append(tuple((field, value)))
(Added line)

self.vars.update(validated_vars)






Am Mo., 19. Apr. 2021 um 23:33 Uhr schrieb Andrew Gavgavian <
***@***.***>:

**Comment by Kkeller83** [comment]
Closed via https://github.com/web2py/py4web/pull/499/commits/ec56f0ba89360c89262adecf4c136b5612c910db
