### ISSUE TITLE
Unauthorized Application/Json Request Not Redirecting

### ISSUE THREAD

**Issue by macneiln** [web2py/py4web#501]
In auth.py the `abort_or_redirect( )` function is raising a 403 Forbidden error when the request `accept` header contains `application/json` instead of doing the standard redirect/appending the next url as it does when the page is loaded directly (not via axois, etc.)

This doesn't seem to add any value that I'm aware of but instead complicates `application/json` requests where the user is not authorized, logged in, etc. and client-side my application is not redirected as anticipated.

My proposal is either to remove it so it functions the same regardless of request type, or if this functionality is required for something then we should add a secondary header to determine whether this functionality should be bypassed if required.

### auth.py
```
    def abort_or_redirect(self, page, message=""):

        """
        return HTTP 403 if 'application/json' in HTTP_ACCEPT
        else redirects to page
        """
        if re.search(REGEX_APPJSON, request.headers.get("accept", "")):
            abort(403)

        redirect_next = request.fullpath
        if request.query_string:
            redirect_next = redirect_next + "?{}".format(request.query_string)
        self.auth.flash.set(message)
        redirect(
            URL(
                self.auth.route,
                page,
                vars=dict(next=redirect_next),
                use_appname=self.auth.param.use_appname_in_redirects,
            )
        )
```

**Comment by valq7711** [comment]
can you provide an example of how you hold redirect using axios?

**Comment by valq7711** [comment]
I mean what does your client side code look like?

**Comment by macneiln** [comment]
> can you provide an example of how you hold redirect using axios?

- I use vuejs, vue-router and axios client-side. 
- Axios sends the request for the page the user has clicked on and the browser automatically handles redirects if they occur and provides me the content from the secondary request (if a HTTP 303 was received), so I end up with the data I'm looking for either way. In this case it would redirect the user to login page before they can get to the page for the link they clicked.

**Comment by valq7711** [comment]
in case of ajax and server-side redirect you will just get full rendered html of login page in the response, so what do you do next? Go to redirected url with full reloading?

**Comment by macneiln** [comment]
I have a custom fixture that handles the different types of requests I send and in the case of the auth specific routes I override/serialize the auth form in my fixture transform function so that it can be returned via json rather than the default auth.html page so no full reload is required once initially loaded.

**Comment by valq7711** [comment]
So it should be 
>This doesn't seem to add any value that I'm aware of  **(as I have custom fixtures that override/serialize auth forms in appropriate format)**

;)
