### ISSUE TITLE
Try from Source: Make from Windows?

### ISSUE THREAD

**Issue by MBfromOK** [web2py/py4web#51]
Just tried to clone this repo from windows with Github desktop, how should windows developers take advantage of source option?

The highest recommendation on Google is msysGit which was superseded by Git for Windows 2.x

**Comment by MBfromOK** [comment]
This might be a moot issue, I was just trying to fix issues with missing / broken favicon files.. Creating another issue report / patch for those.

**Comment by mdipierro** [comment]
This is really a windows question, not a py4web issue, and I do not know windows. ;-)
In the past I have found cygwin to best the best tool for the job.

**Comment by MBfromOK** [comment]
I think this is most likely moot, I was under the impression that assets was a collection of graphics being distributed so that we could experience your look and feel, after I thought about it for a second I realized this was most likely not the case.
