### ISSUE TITLE
Registering does not log in

### ISSUE THREAD

**Issue by lucadealfaro** [web2py/py4web#515]
I am not quite sure this is considered a bug, but it is certainly a surprising behavior.  When one registers, and clicks on "Sign Up", one then has signed up, but has not logged in.  One must then repeat the procedure to log in. 
I understand why this might be the case if login requires email verification or manual approval, but if none of these two apply, why is it that registering does not lead to login?  Should this be fixed?

**Comment by nicozanf** [comment]
There is a [login_after_registration](https://github.com/web2py/py4web/blob/826fb1ae608c26f7f86652506632acb1a5a6bd87/py4web/utils/auth.py#L189) parameter which should achive what you mean. Have you tried it?

**Comment by nicozanf** [comment]
I do confirm that it works as expected. Of course, it requires False VERIFY_EMAIL & REQUIRES_APPROVAL.

I'm adding a LOGIN_AFTER_REGISTRATION parameter to settings.py / common.py  on the _scaffold app in order to make it easier to configure.
