### ISSUE TITLE
MySql Connection Error:

### ISSUE THREAD

**Issue by MBfromOK** [web2py/py4web#53]
**my <app name>/settings.py contains:**
`
DB_URI = 'mysql://<dbuser>:<dbpass>@localhost/<table name>?set_encoding=utf8mb4_general_ci
`

**I can't find a file / place calling MySQL with the 'utf8mb4_0900_ai_ci' setting to change it to my database anywhere!**

How do I call MySQL with my preferred string if not using the string above?

`Traceback (most recent call last):`
    `File "C:\DevSDKs\Python\Python37\lib\site-packages\py4web\core.py", line 684, in import_apps 
        importlib.reload(sys.modules[name])`
    `File "C:\DevSDKs\Python\Python37\lib\importlib\__init__.py", line 169, in 
        reload_bootstrap._exec(spec, module)`
    `File "<frozen importlib._bootstrap>", line 630, in _exec`
    `File "<frozen importlib._bootstrap_external>", line 728, in exec_module`
    `File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed`
    `File "apps\GenMCV\models.py", line 9, in <module>`
        `db = DAL(settings.DB_URI, folder=settings.DB_FOLDER, pool_size=settings.DB_POOL_SIZE)`
    `File "C:\DevSDKs\Python\Python37\lib\site-packages\pydal\base.py", line 171, in __call__obj = super(MetaDAL, cls).__call__(*args, **kwargs)`
    `File "C:\DevSDKs\Python\Python37\lib\site-packages\pydal\base.py", line 477, in __init__
        "Failure to connect, tried %d times:\n%s" % (attempts, tb)`
    `RuntimeError: Failure to connect, tried 5 times:`
        `Traceback (most recent call last):`
            `File "C:\Users\rhlin\AppData\Roaming\Python\Python37\site-packages\mysql\connector\connection_cext.py", line 472, in cmd_query`
                `raw_as_string=raw_as_string)`
                `_mysql_connector.MySQLInterfaceError: Unknown collation: 'utf8mb4_0900_ai_ci'`

**Comment by advh67** [comment]
Are you using mariaDB? The default collation for Oracle's MySQL is utf8mb4_0900_ai_ci and you don't need to specify it.
That's not true for mariaDB. Try executing "SHOW COLLATION" by hand, you will see the list of accepted collations. Examples: utf8mb4_polish_ci,utf8mb4_danish_ci, utf8mb4_spanish_ci,... and so on.

The error is "Unknown collation": utf8mb4_0900_ai_ci is not in the list of collations.

**Comment by MBfromOK** [comment]
Resolved this late last night...

I had tried:

    ?set_encoding=utf8mb4_unicode_ci

and
    
    ?set_encoding=utf8mb4_general_ci

 and had to change it to:

    ?set_encoding=utf8mb4

which based on the table below, the default is utf8mb4_general_ci

[Full Table](https://dev.mysql.com/doc/refman/5.7/en/charset-charsets.html)

| Charset  | Default collation   |
|----------|---------------------|
| utf8     | utf8_general_ci     |
| **utf8mb4**  | **utf8mb4_general_ci**  |
| utf16    | utf16_general_ci    |
| utf16le  | utf16le_general_ci  |

**NOTE:** This doesn't cover any issues / limitations imposed by PyMySql

**Comment by MBfromOK** [comment]
I would be interested in seeing an update to the docs detailing how we should be specifying alternative or specific collations
Also, would it be feasible to create or provide error messages that reflect whether the issue is due to lack of helper module support or overall by the version of MySQL in use? Or would that be a lot of overhead?
