### ISSUE TITLE
Grid buttons in ajax-component cause the page to go to the component's controller

### ISSUE THREAD

**Issue by kevinkosterr** [web2py/py4web#535]
Title might not be that clear, but what i'm trying to say is that. For example, in web2py when you used {{=LOAD}} and you loaded a grid as a component inside the webpage you were able to use the pagination, as well as create/edit/delete records. 

Now, when i press 'Create' the button just takes me to their controller. Say my controllers look like this:
```python
@action('foo_grid/<path:path>')
@action.uses('foo_bar.html', db)
def component_foo_grid():
    grid = Grid(
        db.foo
    )
    return dict(foo_grid=grid)

@action('index')
@action.uses('index.html')
def index()
    message = 'Hello world'
    return dict(message=message)
```

Now inside `foo_bar.html`:
```hbs
[[=foo_grid]]
```

`index.html`:
```html
[[extend 'layout.html']]

<ajax-component id="component1" url="[[=URL('foo_grid')]]">
 <blink>Loading..</blink>
</ajax-component>
```

Now whenever i press the create button, i will just be taken to the `foo_grid` controller instead of staying on the current page.

**Comment by Kkeller83** [comment]
To get around that we are using from and grid with htmx now.

Let me find some of xamples from thr group.

Mostly Jim posted those.

**Comment by jpsteil** [comment]
I know I've been quiet lately.  I was at a conference all of last week and catching up so far this week.  But, reach out with any specific htmx/form/grid questions.  It is all working pretty well for me now, but there are things you have to be careful of. Namely setting the target properly and (in my case) always use hx-swap='innerHTML'.  This messed me up for a while...

**Comment by kevinkosterr** [comment]
@jpsteil could you maybe post an example of this?

**Comment by Kkeller83** [comment]
In the discord channel htmx is the sample and discussion,

Here is also the link to the latest sample from Jim on his Gdrive:

https://mail.google.com/mail/u/0/#search/htmx+jim++zip?projector=1



Am Mi., 19. Mai 2021 um 09:31 Uhr schrieb Kevin ***@***.***>:

**Comment by jpsteil** [comment]
I'm not sure that example is still working with the latest py4web. I'll try to make some time today to update for the current grid.

**Comment by jpsteil** [comment]
I just found some time!  Here is the link for the updated version. You no longer need to have a separate grid.py, this works now with py4web on github.

**Comment by Kkeller83** [comment]
I think you forgot the link though.

**Comment by jpsteil** [comment]
https://drive.google.com/file/d/1Kyb-yhkv3krWZsrzyG9LdEc56kWJNx1t/view?usp=sharing

Thanks Kevin

**Comment by jpsteil** [comment]
FYI - just added it to github too. 

https://github.com/jpsteil/py4web_htmx_demo

**Comment by Kkeller83** [comment]
Thank you Jim!

The custom button class you are using is not imported in the sample though.

So I tried to replace the button with simple HTML button code but it does
not seem to work:

[image: image.png]

Am I doing it wrong?

I am still testing , but really looks great Jim!



Am Mi., 19. Mai 2021 um 14:24 Uhr schrieb Jim Steil <
***@***.***>:

**Comment by Kkeller83** [comment]
Also tried this without success:

 grid.param.new_sidecar =  A("This is my SideCar Button", _class="button",
_href="https://www.google.com")
    grid.param.edit_sidecar = A("This is my SideCar Button",
_class="button", _href="https://www.google.com")



Am Mi., 19. Mai 2021 um 15:16 Uhr schrieb Kevin Keller ***@***.***

**Comment by Kkeller83** [comment]
A false alarm, it works!

I suppose the cancel button then triggers some code to retrieve the
original form via htmlx.

Maybe you can share that too, if you would not mind please :).



Am Mi., 19. Mai 2021 um 15:20 Uhr schrieb Kevin Keller ***@***.***

**Comment by Kkeller83** [comment]
While I am still curious how you solved it, I got the cancel buttons by
just adding a simple page reload:

Just leaving this here for FYI / documentation for fellow testers:

 grid.param.new_sidecar =  A("Cancel", _class="button",
_onclick="window.location.reload()")
 grid.param.edit_sidecar = A("Cancel", _class="button",
_onclick="window.location.reload()")


Am Mi., 19. Mai 2021 um 15:29 Uhr schrieb Kevin Keller ***@***.***

**Comment by jpsteil** [comment]
@kevinkosterr - can this be closed?

**Comment by Kkeller83** [comment]
yep

Am Fr., 16. Juli 2021 um 13:47 Uhr schrieb Jim Steil <
***@***.***>:
