### ISSUE TITLE
"represent" does not work 

### ISSUE THREAD

**Issue by Kkeller83** [web2py/py4web#536]
When putting this code in models.py 

    
my_info = db.define_table('my_info',
    Field('my_uuid', 'string', length=64, requires=[IS_NOT_EMPTY()], unique=True),
    Field('my_name', 'string', length=512, requires=[IS_NOT_EMPTY()]),
    Field('my_type', 'string', length=32, requires=[IS_NOT_EMPTY()]),
)

my_other_info = db.define_table('my_other_info',
    Field('my_other_uuid', 'string', length=64, requires=[IS_NOT_EMPTY()], unique=True),
    Field('my_info_id', 'reference my_info', requires=IS_IN_DB(db, db.my_info.my_uuid),represent=lambda id, row: db.my_info(id).my_uuid),
    Field('my_other_name', 'string', length=512, requires=[IS_NOT_EMPTY()]),
    Field('my_other_type', 'string', length=32, requires=[IS_NOT_EMPTY()]),
)
db.commit()
#

my_other_info.my_info.id should show the value of my_info.my_uuid, but it does not .
Instead it just shows the table id. 
Also of course impossible to add any values like this in my_other_info as IS_IN_DB can never be fullfilled

**Comment by Kkeller83** [comment]
Maybe we can fix this in py4web. In my py4web this works as follows: 

I added this dbrepresent.py code:

https://github.com/Kkeller83/Elliot/blob/master/py4web/utils/dbrepresent.py

and apply this fix to pydal:

https://github.com/Kkeller83/piedal/commit/ec25e8858479b3fb373cb58d21e7620f44847bf8

then you can do this and it works:

from py4web import action, request, abort, redirect, URL
from yatl.helpers import A
from .common import db, session, T, cache, auth, logger, authenticated, unauthenticated, flash
from py4web.utils import dbrepresent


db.representers = {
    'rows_render': dbrepresent.represent
}

@unauthenticated("index", "index.html")
def index():
    rows = db(db.foo.id > 0).select()
    for row in rows.render(): 
        print(row)

    return locals()

**Comment by Kkeller83** [comment]
kevins reply was relating to some other issue that has been resolved meanwhile, but the rows.render issue is still there.

**Comment by jpsteil** [comment]
@kevinkosterr - if you add 'reference person' does that fix your issue?

```
db.define_table('person',
	Field('name', represent= lambda row: row.id),
        )

db.define_table('foo',
	Field('bar'),
	Field('doe', 'reference person', represent=lambda row: row.bar, requires=IS_IN_DB(db, 'person.name')),
	)
```

**Comment by Kkeller83** [comment]
Yes, this solves the previous issue with reference.  Apart from your answer here, it was also solved on Discord with you.  I think I can close this. Thanks Jim!
