### ISSUE TITLE
pydal: blobs get truncated

### ISSUE THREAD

**Issue by Kkeller83** [web2py/py4web#537]
Crhis from the py4web forum brought this up: 

Making more test when pydal retrieve the blob data from the db is only getting just a part of the information.

When in print the rows after the select i get a small sample like this:

images = cherry_db(cherry_db.image.node_id == i['node_id']).select(cherry_db.image.node_id, cherry_db.image.png)

for m in images:
   print(m['png’])

b'<\xd1\x88\x1c4l\x04\x84\xce 0\x13\xc6\x01\r\xdd\xd0'

Maybe it belongs to the pydal repo, but I thought its good to bring it up here too.

**Comment by valq7711** [comment]
I've made and tested a simple app that stores/retrieves png-image as blob - works fine for me
