### ISSUE TITLE
Grid button with append_id=True doesn't append row id correctly when url contains a query string or hash fragment

### ISSUE THREAD

**Issue by anonymous378** [web2py/py4web#543]
Assume a GridButton class has been defined, and the following argument is supplied to a Grid instantiation...

`post_action_buttons=[GridButton(URL("table", table_name, "delete", vars=dict(x=1), hash='y'), "Delete", icon="fa-trash", append_id=True)]`

...then the URL link for the button wrongly becomes...

`/{script_name?}/{app_name?}/table/{table_name}/delete/?x=1#y/{row_id}`

...with the row id concatenated after the query string and hash fragment instead of at the end of the path where it belongs.

The offending code is in py4web/utils/grid.py in the `render_action_button` method:

```
        if row_id:
            url += "/%s" % row_id
```

That code is going to need to parse the url components in order to insert the row_id at the correct position.

**Comment by jpsteil** [comment]
I think you can provide callables to those buttons now.  That would allow you much more control over how the button is generated. Have you tried that?

**Comment by anonymous378** [comment]
@jpsteil: Ah, thank you, I wasn't aware of that...the callable url is indeed what I needed!

**Comment by jpsteil** [comment]
Can you pull the latest py4web from the repo?  There is a new feature in Grid where you can now specify a Column() object as well as database fields in the fields argument.  Column is a callable that is passed all the data included in the row. You should now be able to build anything imaginable to place inside a column cell.

**Comment by qualityliquidfeeds** [comment]
I believe this issue can be closed.
