### ISSUE TITLE
RFC - Use Renoir templating engine in py4web/yatl

### ISSUE THREAD

**Issue by gi0baro** [web2py/py4web#547]
Hi all,
quite a long time since my last commit in web2py repos. Here is a change proposal to use [Renoir](https://github.com/emmett-framework/renoir) templating engine in place of the actual implementation (YATL).

### Summary

[Renoir](https://github.com/emmett-framework/renoir) template engine comes from a major rewrite of the web2py templater, outsourced from Emmett, firstly released as an independent project in Jan 2020. It currently supports Python versions from 3.6 to 3.9, it doesn't require any additional dependency and is released under BSD license.

Its syntax is completely compatible with web2py (and thus with YATL/py4web).

### Rationale

The main reason behind this proposal is to re-unify the codebase of the two projects, giving the chance to py4web and its community to benefit from the enhancements introduced in web2py templater in the last ~6 years of Emmett development.

Obviously, the operation will also introduce the indirect benefit of unify issues, bug triage, enhancements introduction and community, giving thus the chance to make the templating language stronger and popular.

### Benefits

- Adopt modern code
- Support and tests for recent Python versions
- Support for [escaping](https://github.com/emmett-framework/renoir/blob/master/docs/quickstart.md#escaping)
- Support for relative paths in `extend`/`include` instructions
- Support for [extensions](https://github.com/emmett-framework/renoir/blob/master/docs/extensions.md#extensions) like [renoir-haml](https://github.com/gi0baro/renoir-haml)

### Risks

- Splitting the community support across different projects

### Benchmarks

I conducted a super-simple benchmark (might be imprecise), using a simple template:

```html
<div class="posts">
    {{ for idx, post in enumerate(posts): }}
    {{ cssclass = 'white' if idx % 2 else 'gray' }}
    <div class="post {{ =cssclass }}">
        <p>{{ =post['text'] }}</p>
    </div>
    {{ pass }}
</div>
```

and the following code:

```python
import time
from yatl import render as yrender
from renoir import Renoir

POSTS = [
    {"text": "foo"},
    {"text": "bar"},
    {"text": "baz"}
]

def yatl():
    with open("template.html", encoding="utf8") as stream:
        data = stream.read()
    t = time.time()
    for _ in range(20_000):
        yrender(data, context={"posts": POSTS})
    print(f"YATL: {time.time() - t}")

def renoir():
    r = Renoir()
    t = time.time()
    for _ in range(20_000):
        r.render("template.html", {"posts": POSTS})
    print(f"Renoir: {time.time() - t}")

yatl()
renoir()
```

which produced the following results:

```
giovanni@Deneb ~/Downloads/yatl-test ❯ python test.py
YATL: 6.142576217651367
Renoir: 0.4085378646850586
```

### Conclusions

Considering all the upper points, and given the community express its interest in the proposal, I can produce a PR containing the code changes.

Let me know!
Ciao

**Comment by mdipierro** [comment]
Is it backward compatible? How about the yatl helpers? Do they exist in
Renoir? If not, cay they be backported?

**Comment by gi0baro** [comment]
> Is it backward compatible? 

@mdipierro The syntax/lexers are the same of web2py, the minimum Python version is 3.6 (thus I imagine yes for py4web, no idea about web2py)

> How about the yatl helpers? Do they exist in Renoir? If not, cay they be backported?

We can inject the YATL helpers in the context via extension or subclassing.

**Comment by mdipierro** [comment]
I am fine with using Emmet since it is faster. we should not depend on both
yatl and emmet so either we move the helper to
py4web/utils/html_helpers.py, or you include them in Emmet, or we make its
own project. Thoughts?

**Comment by Kkeller83** [comment]
Cool to see you back Giovanni !

**Comment by gi0baro** [comment]
> I am fine with using Emmet since it is faster. we should not depend on both yatl and emmet so either we move the helper to py4web/utils/html_helpers.py, or you include them in Emmet, or we make its own project. Thoughts?

@mdipierro Emmett already contains its own html helpers, Renoir doesn't since they're out of its scope.
I'm for moving the helpers in py4web. Gonna open a PR in this sense.

**Comment by Kkeller83** [comment]
This is a great idea. Only concern I have is that grid.py (py4webs html grid generator) and form.py (py4webs html Form generator) and many other components in py4web (like the Auth forms etc) depend heavily on the yatl helpers. I hope we can find a way to make this a smooth transition. Other than that I am excited about this. Maybe down the line we find further areas to collaborate.

**Comment by mdipierro** [comment]
The way i see it please who have yatl installed will continue in mopey from
it. New apps will instead import helpers from pydal.utils.htmlhelpers

**Comment by gi0baro** [comment]
@mdipierro I pushed #548. Tests passing, but it probably requires a bit of manual checks

**Comment by mdipierro** [comment]
Will try process this later today.

 Maybe we should continue import helpers from yatl and have yatl depend on
Renoir. Just thinking aloud.

**Comment by lucadealfaro** [comment]
I would just beg for backwards compatibility on this -- not to  break in a single shot all the apps.

**Comment by lucadealfaro** [comment]
This includes the imports.  Too many places where one writes 
from yatl import *

**Comment by lucadealfaro** [comment]
More context: the reason I beg for backwards compatibility is that I don't want to break all of the dozen of apps (see linked repos) and videos in [learn-py4web.github.io](https://learn-py4web.github.io) .  It's not a matter of fixing one or two apps.

**Comment by gi0baro** [comment]
@lucadealfaro actually since I didn't touch `yatl`, and the pypi package is still there, everything should still work as expected. Then we can update docs to point to new importable modules..
