### ISSUE TITLE
Boolean field not writable at insert

### ISSUE THREAD

**Issue by wasimbaig** [web2py/py4web#552]
Py4web: 1.20210522.2 on Python 3.8.5 (default, Jan 27 2021, 15:41:15) 
[GCC 9.3.0]

_scaffold app, sqlitedb

db.define_table('settings', Field('active', 'boolean', default=True))

1. checkbox not clickable in 'Create' _dashboard/dbadmin?app=boolean1&dbname=db&tablename=settings, however, editing record works fine, checkbox is clickable

2. if default=True, checkbox displays unchecked, however, on insert, row value is True

3. GRID +New doesn't take default value from Field, and editing doesn't work either

**Comment by Eudorajab1** [comment]
I am seeing same behaviour

**Comment by jpsteil** [comment]
I just tested with the latest py4web and it worked for me.  Are you running the latest code from git?

I tested a boolean field with no default and I tested with default=True.  Both worked as I expected them to.

Can you try with latest py4web (don't forget to update requirements) and comment back?

**Comment by wasimbaig** [comment]
No change in behavior after latest git and requirements update.

```
Py4web: 1.20210619.1 on Python 3.8.5 (default, May 27 2021, 13:30:53) 
[GCC 9.3.0]
```

To replicate, create new app, in models.py add

```
db.define_table('settings', Field('active', 'boolean', default=True))
db.commit()

```
http://127.0.0.1:8000/_dashboard/dbadmin?app=test2806&dbname=db&tablename=settings

![image](https://user-images.githubusercontent.com/16080/123564833-4d9b6400-d7d4-11eb-80d3-996f08d9f114.png)
its not checked, nor is it clickable, but saving it will show default value (i.e. True)
 
![image](https://user-images.githubusercontent.com/16080/123564862-6c99f600-d7d4-11eb-8ace-77bb760918a1.png)

Editing, it will toggle.
![image](https://user-images.githubusercontent.com/16080/123564882-81768980-d7d4-11eb-8769-900ca2564e74.png)

Am available for any testing, thanks Jim!

**Comment by jpsteil** [comment]
Have you tried outside of the Admin interface?  I wasn't testing it there, just inside an app of mine.

**Comment by jpsteil** [comment]
I just tested in the Admin interface and can confirm it isn't picking up the default there.

**Comment by agavgavi** [comment]
Hopefully this PR fixes it, it was an issue with Vue's reactivity on objects and some incorrectly called arguments.
