### ISSUE TITLE
represent does not work with rows render

### ISSUE THREAD

**Issue by Kkeller83** [web2py/py4web#570]
if you use rows.render() in py4web you will get an error. 

Maybe we can fix this in py4web. In my py4web  fork this works as follows:

I added this dbrepresent.py code:

https://github.com/Kkeller83/Elliot/blob/master/py4web/utils/dbrepresent.py

and apply this fix to pydal:

Kkeller83/piedal@ec25e88

then you can do this and it works:

from py4web import action, request, abort, redirect, URL
from yatl.helpers import A
from .common import db, session, T, cache, auth, logger, authenticated, unauthenticated, flash
from py4web.utils import dbrepresent

db.representers = {
'rows_render': dbrepresent.represent
}

@unauthenticated("index", "index.html")
def index():
rows = db(db.foo.id > 0).select()
for row in rows.render():
print(row)

return locals()

**Comment by mdipierro** [comment]
this was fixed some time ago
