### ISSUE TITLE
the current Scaffold app import deprecated py4web.utils.tags module

### ISSUE THREAD

**Issue by nicozanf** [web2py/py4web#590]
At startup, py4web complains about  the Scaffold app which is importing a deprecate module:

[ ] loading _scaffold ...
WARNING:root:Deprecation notice: replace py4web.utils.tags with pydal.tools.tags

The error goes away if you just change accordingly the import line one on common.py.  Are there any side effects?

**Comment by jpsteil** [comment]
This was a change from a week or so ago.  No, there will be no side-effects.  That line should be updated in all apps included with py4web.

**Comment by nicozanf** [comment]
Fine, so  I've made a PR ;-)
