### ISSUE TITLE
To-be-or-not-to-be: py4web2.0

### ISSUE THREAD

**Issue by valq7711** [web2py/py4web#637]
Hey guys,  let's discuss!
https://github.com/web2py/py4web/tree/futuristic
To play with, it requires https://github.com/valq7711/omfitt installed (only from github at the moment)

The main idea is apps-as-components with parameters.
Flask has blueprints - we should have something like that too!
This breaks backward compatibility, but I think it will require some fairly simple fixes in existing projects.
See `apps/todo` and `apps/tst`   - the latter reuses the former as part of the application.
Of course there is work to be done (path/naming resolution, dependency tracking for reloader, ...), but the core functionality is done.
So the question is - does this make sense?

**Comment by SY-MEDIA** [comment]
Sounds like this would encourage a more modular-functions style of building applications. If that's the case, I'm all for it.  I think that approach can eventually evolve to a much more integrated and automated way of building (from larger and larger pre-tested components and application-domain-specific-frameworks) applications from visual design documents or models.

**Comment by mdipierro** [comment]
I think a guiding principle should be to make the user experience for new users simpler. I think what you propose is powerful but makes it harder to bootstrap an app for a new user. Can this logic be in an optional module?

**Comment by valq7711** [comment]
@mdipierro 

Minimal app could be:
```python
from py4web import Action

action = Action()  # just this one extra line

@action("index")
def index():
    return "Hello World"
```



Regular app with common.py:
```python
# common.py
from py4web import Action, FixtureShop, Session

@FixtureShop.make_from # +1 
class shop:            # +1 
    session = Session()

action = Action(shop)      # +1

# as a result: +3 extra lines  
```

```python
# controllers.py

# import only 'shop' instead of `session, db, flash, ...` 
from .common import action, shop  


# enumerate in `action.uses()` only fixtures that are wrapper-first, i.e. pre/post-processors 
# other fixtures are initialized when accessed via `shop.fixture`
@action('index')
@action.uses('index.html')  
def index():
    session = shop.session
   ...

```

**Comment by Kkeller83** [comment]
I like this being optional as well. Just as with flask. If it's optional I am all for it

**Comment by valq7711** [comment]
OK, `Action` and `fixture shop` can be an optional module. But the main problem is the current fixtures processing, here are the suggestions:

### `transform`, `on_error`, `on_success`   hooks should be replaced with one `on_output(self, ctx)`
where `ctx` - request context object holding process info, e.g.:
```
process_phase:  SETUP | RUN | OUTPUT | FINALIZE
used_fixtures: 
output: current output
last_exception:  
exceptions: exceptions stack - [(process_phase, exception), ...]

```
The reasons: 
 - The fixture should decide how the exception should be handled (success or error)
 - `transform` is not a good name and makes a mess:
 https://github.com/web2py/py4web/blob/32256e683787aef53ed914ac7ad50f288f1bb88f/py4web/utils/auth.py#L292-L296
The above has nothing to do with the output transformation.

### post-processing hooks should be processed in reverse order
The reasons: 
 - it is the most expected behavior, since fixtures act as decorators/middleware, don't they?
 - the problem example: let's say we want to create a logger that needs to write something to the session - currently we cannot do that in `logger.on_success/on_error/finalize` because the session hooks will be handled first (i.e. closing the session), so we have to do that in the `transform` hook, that seems like a hack.

**Comment by mdipierro** [comment]
We had log of discussion on this topic. We settled on the current design which allows Fixture to manipulate context and one can create custom decorators that combine multiple fixtures.
