### ISSUE TITLE
Doc: Chapter-13 falsely states "py4web runs on Python 3.6+"

### ISSUE THREAD

**Issue by vincentborghi** [web2py/py4web#643]
The first item in the first bulleted list of the "From web2py to py4web" refers two times to Python 3.6 as the minimum version, while it apparently must be Python 3.7.

[PS: I tried an install first with a python 3.6 and it did not work (rocket3 and ombott requisites, at least, were not installed). I finally installed py4web with a python 3.9. In the meantime, I've read elsewhere that 3.7 is the minimal version).]

Thanks

**Comment by mdipierro** [comment]
Thanks for pointing it out. We will fix it
