### ISSUE TITLE
feature request/question for https://py4web.com/_dashboard

### ISSUE THREAD

**Issue by JoeCodeswell** [web2py/py4web#653]
Dear py4web folks,

Would it be hard to put the examples app live on 
https://py4web.com/

to be accessed with the url

https://py4web.com/examples

Thanks for the great work.

Love and peace,
Joe Dorocak

**Comment by jpsteil** [comment]
Hi Joe

That decision will be up to Massimo, I think he maintains the py4web.com site.

If you're looking for some other samples I have a couple on my site:

https://simple_table.pythonbench.com/
https://southbreeze.pythonbench.com/

Simple Table is a site I created when I was playing around with different py4web grid options in the Summer of 2020. 

SouthBreeze is a sample app I put together to show how you can do parent/child grids using htmx and py4web.

Let us know on the google group or in Discord if you have any questions.

**Comment by JoeCodeswell** [comment]
Thanks SO MUCH, Jim.
Love and peace,
Joe

**Comment by jpsteil** [comment]
thanks Joe - I'm using letsencrypt there and can't say that I fully understand how to renew multiple certs on one box. Seems to be working for the most part, but seems like one always gets missed.

I'll take a look at it.

**Comment by mdipierro** [comment]
I will add the examples but need to tweak them so that different users do
not share info accidentally.

**Comment by JoeCodeswell** [comment]
Dear Jim,

I must admit I don't understand that stuff either. 
Thanks for checking it out.
Love and peace,
Joe

**Comment by JoeCodeswell** [comment]
Dear Massimo,
Thanks for the GREAT NEW WORK.
Thanks for the attention to EXAMPLES!   :)
Love and peace,
Joe

**Comment by mdipierro** [comment]
I am sorry this has not happened yet. Problem is that examples needs major rewrite to make sure one users are isolated from each other. Right now it uses one database, not per user.

**Comment by mdipierro** [comment]
This was done. except /examples became /showcase. Not all examples are available on the public web page, some must run locally because require a db
