### ISSUE TITLE
_thread._local' object has no attribute 'language'

### ISSUE THREAD

**Issue by sunjian-github** [web2py/py4web#665]
I am writing a demo use example table——person, I want to show all the person in html file
then  a error was found ,please help me ,thanks very much

`'_thread._local' object has no attribute 'language'`

**1.the controller is**
```
@action("ps", method=["GET", "POST"])
@action.uses(db,"person.html")
def ps():
    form = Form(db.person)
    rows = db(db.person).select()
    return dict(form=form, rows=rows)
```

**2.person.html** 
`[[extend 'layout.html']]
[[=form]]
[[=rows]]
`

**Comment by Kkeller83** [comment]
Could w see your models please?

**Comment by sunjian-github** [comment]
yes ,model file 
`# simple table example
db.define_table(
    'person',
    Field('name', requires=IS_NOT_IN_DB(db, 'person.name'), label=T('name')),
    Field('job', requires=IS_NOT_EMPTY(), label=T('job')),
    format='%(name)s',
)
`

**Comment by agavgavi** [comment]
Try adding the translator object T to your action.uses before the db. It should be the same T you are importing in your model.

**Comment by sunjian-github** [comment]
After adding the translator object T to my action, Solved the problem.
thank you @Kkeller83 @agavgavi
