### ISSUE TITLE
Dashboard error "sqlite3.OperationalError: database is locked"

### ISSUE THREAD

**Issue by nicozanf** [web2py/py4web#669]
This problem was  first reported by donal...@gmail.com <donaldm2020@gmail.com> on the [mailing list ](https://groups.google.com/d/msgid/py4web/22f6cfcc-b024-429f-87a3-e3db673cb2e9n%40googlegroups.com?utm_medium=email&utm_source=footer) and also on Discord.
It's probably caused by this change: "version 1.20211208.1 - require threadsafevariable 1.2"

It seems to affect all environments. For example with the standard _scaffold app, using the Dashboard app to modify any database value gives a traceback like the one attached. Note that the first change seems succesfull (but it's not really written on disk!) while all the others fail with the same error until the framework is restarted.

**Comment by nicozanf** [comment]
[traceback.txt](https://github.com/web2py/py4web/files/7816566/traceback.txt)

**Comment by DonaldMcC** [comment]
Just to confirm it is the threadsafe variable 1.2 commit on 9th Dec that causes the issue.  I am not really clear what this aimed to achieve and whether the changes to __init__.py of the dashboard app are actually required?  Looks like the first API call reports success (http2000) but doesn't actually finish/write to the database or error and becuase first call is stuck it correctly reports a lock on subsequent call.

https://github.com/web2py/py4web/commit/a094d3ea41b9b0aadcd1d51a9fad90c7dfc536d3

**Comment by mdipierro** [comment]
It should not be causing that issue unless something is put in
threadsafelocal that does not belong there. This will be fun to debug.

**Comment by mdipierro** [comment]
Issue was resolved in version 1.20220106.1
