### ISSUE TITLE
"Table 'mydb.mytable1' doesn't exist"

### ISSUE THREAD

**Issue by MBfromOK** [web2py/py4web#69]
Ok, I have spent 2 hours trying to figure either what is causing this, or a way around this error.

# What I want:
    Match the functionality of /examples/models.py:
         - declare tables and then insert data from backups or online sources (when they are available)

# What I am getting 

### Error (Part 1):
```
Traceback (most recent call last):
    File "D:\Dev\GitHub\MBfromOK\py4web\py4web\core.py", line 679, in import_apps
        module_name, init).load_module()
    File "<frozen importlib._bootstrap_external>", line 407, in _check_name_wrapper
    File "<frozen importlib._bootstrap_external>", line 907, in load_module
    File "<frozen importlib._bootstrap_external>", line 732, in load_module
    File "<frozen importlib._bootstrap>", line 265, in _load_module_shim
    File "<frozen importlib._bootstrap>", line 696, in _load
    File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
    File "<frozen importlib._bootstrap_external>", line 728, in exec_module
    File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removeD
```
### Relevant Part:
    File "apps\testing\__init__.py", line 7, in <module>
        from . models import db
    File "apps\testing\models.py", line 149, in <module>
        if not db(mydb.table1).count():

### Error (Part (2):
```
    File "C:\DevSDKs\Python\Python37\lib\site-packages\pydal\objects.py", line 2395, in count
        return db._adapter.count(self.query, distinct)
    File "C:\DevSDKs\Python\Python37\lib\site-packages\pydal\adapters\base.py", line 791, in count
    self.execute(self._count(query, distinct))
  File "C:\DevSDKs\Python\Python37\lib\site-packages\pydal\adapters\__init__.py", line 67, in wrap
    return f(*args, **kwargs)
  File "C:\DevSDKs\Python\Python37\lib\site-packages\pydal\adapters\base.py", line 413, in execute
    rv = self.cursor.execute(command, *args[1:], **kwargs)
  File "C:\DevSDKs\Python\Python37\lib\site-packages\MySQLdb\cursors.py", line 209, in execute
    res = self._query(query)
  File "C:\DevSDKs\Python\Python37\lib\site-packages\MySQLdb\cursors.py", line 315, in _query
    db.query(q)
  File "C:\DevSDKs\Python\Python37\lib\site-packages\MySQLdb\connections.py", line 226, in query
    _mysql.connection.query(self, query)
MySQLdb._exceptions.ProgrammingError: (1146, "Table 'mydb.table1' doesn't exist")
```

# What I Have: 
- empty db
- db user with permissions
- completely empty table: table1
- models.py containing

### Code (Part 1):
```
db = DAL('mysql://test:testing@localhost/test?set_encoding=utf8mb4')
```
### Code (Part 2):
```
db.define_table(
    'table1',
    Field('code', 'integer', required=True, unique=True),
    Field('name', 'string', length=256, required=True, requires='text'),
    Field('manager', 'string', length=256),
    Field('phone'),
    Field('address', 'string', length=256),
    Field('zip', 'string', length=256),
    Field('latitude', 'decimal(8,6)', required=True),
    Field('longitude', 'decimal(8,6)', required=True),
    Field('facilitytype', 'text', length=256),
    format='%(name)s'
)
db.commit()
```
### Code (Part 3):
```
if not db(db.table1).count():
    # Call a script to retrieve the sites list - from both server and test
    print('Sites contains no data')
    if offlinetesting:
        print('\n\n\tTesting offline...\n\n')
        myfilepath = Path(Path(__file__).parent).as_posix()
        if not Path('.', 'sitelistgeo.csv').exists():
            print("sitelistgeo.csv missing")
        else:
            try:
                sitelist = bs(myfilepath)
            except Exception as Error:
                print(Error)
                pass
    else:
        # TODO Load content from an online source
        #  Should check if it has been updated first
        pass
    # After the script runs add the result to the sites table
    try:
        sitelist
    except NameError:
        sitelist = None
    finally:
        if not sitelist is None:
            for site in sitelist:
                if not site[0] == 'Code':
                    db.sites.insert(
                        code=site[0],
                        name=site[1],
                        manager=site[2],
                        phone=site[3],
                        address=site[4],
                        zip=site[5],
                        latitude=site[6],
                        longitude=site[7],
                        type=site[8]
                    )
            db.commit()
        else:
            if not Path('.', 'sitelistgeo.csv').exists() and offlinetesting:
                print('Offline Testing: True\n\tsitelistgeo.csv: File not found')
```

**NOTE:** Code 2 & 3 were originally back to back 

# What I tried so far:

- Added a Try clause to detect if the table exists
- Tried a while loop to declare the table until it was successfully created
- Complete delete and reclone of py4web
- Complete delete and wipe of MySql Database
- Complete delete and wipe of MySql instance
- Moved Code 3 to the bottom of models.py (after all the tables are declared)
- Last attempt: Removed Code 3: - Works, but now the table has no data.

**Comment by MBfromOK** [comment]
After sleeping on it, could it be that there is a race condition being created here?

Another wards, could it be that the execution is processing / working in such a way that the table is still being created when the program gets to the line checking if there is data (Line 2: **Relevant Part**) and fails because it doesn't exist yet. (eg. are these DAL calls queued or asynchronous)

**Comment by mdipierro** [comment]
Do not think so. But try check later today

**Comment by mdipierro** [comment]
Auto complete errore. I will try check it later. 😀

**Comment by MBfromOK** [comment]
This does seem to be a race condition...

### My current "fix" / workaround:
```
while not 'table1' in db.tables():
    setCount += 1
    print("No 'table1' table - Loop: ", setCount)
    define_table1_table() _= db.define_table('table1', <Fields>, format='%(name)s')_
    time.sleep(.750)
print("Inserting 'table1' data...")
while not db(db.table1).count():
    try:
        setCount += 1
        set_table1_data(setCount) _for loop: load a file / online source - db.table1.insert()_
    except Exception as Error:
        print(Error)
        time.sleep(.750)

**Comment by mdipierro** [comment]
I cannot reproduce your problem in any way. Can you please create the smallest possible app to reproduce and post it here along with the steps to trigger the error?

**Comment by MBfromOK** [comment]
I have been running this from a USB XAMPP because the production environment is a completely separate network and location, I am spinning up a TurnKey MySQL now to make sure it isn't some kind of USB transfer latency issue.  The workaround above is working but doesn't seem normal or ?pythonic?.

Will build the test app shortly after testing the TurnKey aspect.

**Comment by MBfromOK** [comment]
This was apparently a race condition / lag / buffer issue caused by running xampp from a USB 3.0 flashdrive.  I have setup a dedicated MySQL VM and this issue hasn't occurred for 5+ tests.

I am building code for several more (larger) tables, will reopen if this returns.

Thanks for time and patience!
