### ISSUE TITLE
Grid Column Help Request

### ISSUE THREAD

**Issue by JoeCodeswell** [web2py/py4web#701]
Dear py4web folks,

I have been trying to make an image show up in a Grid Column. 

I have been SOMEWHAT successful:
![py4webGridColumnCapture](https://user-images.githubusercontent.com/3194021/159137787-44c3d997-2061-4e14-ab58-2f0841dd8ded.PNG)

Here's the good-ISH column code:
```python
Column("img12 -img6 -img11  selected:'Misc' ", lambda row: XML(  {"Exercises": '<img src="images/workout-exercise.gif"></img>', "Meds": '<img src="images/pill-happy-pill.gif"></img>' , "Misc": '<img src="images/tempo-time.gif"></img>' ,}['Misc'] ) ), #  WORKS. Thanks, Holy Trinity!!!
```

However, when I try to select WHICH via `{row.msgtype}` I get, "ValueError: Circular reference detected".
Here's the offending Column code:
```python
Column("img12 -img6 -img10", lambda row: XML(  {"Exercises": "images/workout-exercise.gif", "Meds": "images/pill-happy-pill.gif", "Misc": "images/tempo-time.gif",}[f"'{row.msgtype}'"] ) ), #  Circular reference detected
```

Any ideas what I m doing wrong?

Thanks in advance for the help.

Love and peace,
Joe Dorocak

**Comment by jpsteil** [comment]
Hi Joe, sorry for the late response, I've been away for a few days.

I coded up a test and this is working for me:

```python
Column(
    "img12 -img6 -img10",
    lambda row: XML(
        {
            "Desktop": f'<img src="{URL("static", "images/bw_logo.png")}"</img>',
            "Laptop": f'<img src="{URL("static", "images/qlf.gif")}"</img>',
        }.get(row.asset_type.name, row.asset_type.name)
    ),
    required_fields=[db.asset_type.name],
),
```
Should be easy to translate back to your use case.

**Comment by JoeCodeswell** [comment]
Thanks SO MUCH, JP.

I will be SURE to use your code.

Also, I did some snooping around & found `grid.formatters` which ORIGINALLY had similar problems. 

I upgraded py4web & did a little debugging and found that if i said: 
`grid.formatters = {'message.msgtype': lambda value: XML( str(imgD.get(value)) ) }`
instead of 
`grid.formatters = {'message.msgtype': lambda value: XML( imgD.get(value) ) }`
`grid.formatters`  showed an appropriate picture gif.

That made me think `imgD.get(value)`  & so XML() might be having trouble rendering `\"`   contained in the string.

Here's the debugging steps I did for `grid.formatters` in case it might benefit someone else.

```python
   imgD = {"Exercises": '<img style="width: 10%;" src="images/workout-exercise.gif">Exercises</img>',
    "Meds": '<img style="width: 10%;" src="images/pill-happy-pill.gif">Meds</img>' , 
    "Misc": '<img style="width: 10%;" src="images/tempo-time.gif">Misc</img>' ,}

    # debug  4
    grid.formatters = {'message.msgtype': lambda value: XML(str(imgD.get(value))) } 
    # ==SHOWS==> picture of gif + Exercises
    # ==INSPECT==> <td class="grid-cell-type-string grid-col-message_msgtype is-small" style="vertical-align: top; text-overflow: ellipsis;"><img style="width: 10%;" src="images/workout-exercise.gif">Exercises</td>
    # ==SCREENSHOT==> C:\Users\joeco\OneDrive\1d\py4web\Screenshot 2022-03-22 092748.png

    # debug  3 yields   SyntaxError: invalid syntax. Perhaps you forgot a comma?  
    # grid.formatters = {'message.msgtype': lambda value: XML("<img style="width: 10%;" src="images/workout-exercise.gif">Exercises</img> ") }  
    
    # debug  2 yields   WORKS  
    # grid.formatters = {'message.msgtype': lambda value: XML('<img style="width: 10%;" src="images/workout-exercise.gif">Exercises</img> ') }  
    # ==SHOWS==> picture of gif + Exercises
    # ==INSPECT==> <td class="grid-cell-type-string grid-col-message_msgtype is-small" style="vertical-align: top; text-overflow: ellipsis;"><img style="width: 10%;" src="images/workout-exercise.gif">Exercises </td>
    # I think imgD.get(value)  might be having trouble with  \"   contained in the string

    # debug  1 yields message.type
    # grid.formatters = {'message.msgtype': lambda value: imgD.get(value) }   
    # ==SHOWS==> <img style="width: 10%;" src="images/workout-exercise.gif">Exercises</img>  
    # ==INSPECT==> <td class="grid-cell-type-string grid-col-message_msgtype is-small" style="vertical-align: top; text-overflow: ellipsis;">&lt;img style="width: 10%;" src="images/workout-exercise.gif"&gt;Exercises&lt;/img&gt;</td>

    # debug  0 new py4web version says sequence item 0: expected str instance, NoneType found
    # grid.formatters = {'message.msgtype': lambda value: XML( imgD.get(value) ) }   # WORKED Thanks Holy Trinity  ONCE but not next day  
    # grid.formatters = {'message.msgtype_gif': lambda value: XML( imgD.get(value) ) }   # OLD version of py4web  Circular reference detected

    return dict(grid=grid)

```
Here's a screenshot of the result.

<img width="377" alt="Screenshot 2022-03-22 092748" src="https://user-images.githubusercontent.com/3194021/159532633-54b5e144-1bcd-454d-b123-c3d2f9d8954e.png">

As i said, I'll be SURE to use your code because I think `Column` is superior to `grid.formatters`.

Please let me know if i can answer any questions about my `grid.formatters` code.

Thanks again, JP.

Love and peace,
Joe

**Comment by JoeCodeswell** [comment]
Dear Jim,

Your Column code WORKS LIKE A CHAMP!
```python
Column("img12 -img6 -img10", lambda row: XML(  {"Exercises": f'<img src="{URL("static", "images/workout-exercise.gif")}"</img>', 
        "Meds": f'<img src="{URL("static", "images/pill-happy-pill.gif")}"</img>', 
        "Misc": f'<img src="{URL("static", "images/tempo-time.gif")}"</img>', 
    }.get(row.msgtype, row.msgtype) ), 
    required_fields=[db.message.msgtype], ), #  joe's translation

```
Here's a screenshot along with the old `grid.formatters`.
<img width="333" alt="Screenshot 2022-03-22 112440" src="https://user-images.githubusercontent.com/3194021/159550417-714bc214-3a98-49dd-9ac4-78d1b50e5be1.png">

Thanks again, Jim.

Love and peace,
Joe
