### ISSUE TITLE
Suggestion: add a YATL `if (allowed_actions)` condition to _scaffold/templates/layout.html Right menu

### ISSUE THREAD

**Issue by JoeCodeswell** [web2py/py4web#714]
Hi py4web folks,

I suggest we add a YATL `if (allowed_actions)` condition to _scaffold/templates/layout.html Right menu.

Here's the code.

Was:
```html
<li><a href="[[=URL('auth/profile')]]">Edit Profile</a></li>
```
Now:
```html
[[if 'profile' in globals().get('actions',{}).get('allowed_actions',{}):]]
    <li><a href="[[=URL('auth/profile')]]">Edit Profile</a></li>
[[pass]]

```
Thanks.
Love and peace,
Joe

**Comment by mdipierro** [comment]
I have given some thought to this and web2py used to do something like this. Problem is that it is not very portable when the template is copied from a third party theme. I think it is cleaned if the developer manually deletes actions actions from the menu that are not allowed.
