### ISSUE TITLE
provide auth callbacks

### ISSUE THREAD

**Issue by zejdad** [web2py/py4web#721]
It would be practical if Auth fixture allows custom callbacks for actions. 

As a hack for the missing functionality, I am using this Fixture to get a notification upon  user registration which requires admin approval:

```
class NotifyAdminOnRegister(Fixture):
    def __init__(self, mail_admin): self.mail_admin = mail_admin # mailing function
    def on_request(self, context): pass
    def on_error(self, context): pass
    def on_success(self, context):
        if context["status"] == 303:
            try:
                action = request.fullpath.split("/")[-1]
                if action == "register":
                    username = request.forms.get("username")
                    if username:
                        self.mail_admin(subject=f"{request_hostname()} new registration", body=f"user: {username}")
            except Exception as e:
                print(e)
```

Massimo's proposal:

auth.callback_before["login"] = lambda : ...
auth.callback_success["login"] = lambda : ...
auth.callback_failure["login"] = lambda : ...

The difficulty here is figuring out what should be passed to the lambda that is general enough to cover all use cases and easy to remember. Maybe nothing and users will inspect auth to get what they need?

David:

Since almost everything else is accessible via globals, I would consider passing context.

**Comment by mdipierro** [comment]
We implemented some time ago:

auth.on_accept['login'] = lambda form, user: print(form, user) 

The on_accept callback can do a redirect if needed.
