### ISSUE TITLE
Form Double Submission Error

### ISSUE THREAD

**Issue by jadlow** [web2py/py4web#723]
The submit button on a Form has to be clicked twice for the submission to go through. I encountered this error after pulling the latest version of py4web from repository.

**Comment by jpsteil** [comment]
I'm not seeing that behavior.  Do you have some code you could share?  Is it happening in any of the sample apps?

**Comment by jpsteil** [comment]
I have found an instance where I can recreate the problem.

**Comment by jpsteil** [comment]
Submitted PR 725 -> https://github.com/web2py/py4web/pull/725
