### ISSUE TITLE
showcase missing some modules

### ISSUE THREAD

**Issue by mauriziobrilli** [web2py/py4web#732]
As required by Massimo, I checked out the #730  showcase branch and started testing locally.

First issue I met is that several modules that controllers.py tries to import do not exist. Here is a list of the missing modules:

from .examples.vue_file_uploader import vue_file_uploader
from .examples.vue_grid import vue_grid
from .examples.vue_grid_bulma import vue_grid_bulma
from .examples.vue_star_rater import vue_star_rater
from .examples.vue_star_rater_bulma import vue_star_rater_bulma

    from .examples.create_form import create_form
    from .examples.update_form import update_form
    from .examples.vue_form import vue_form
    from .examples.vue_form_bulma import vue_form_bulma
    from .examples.vue_insert_form import vue_insert_form
    from .examples.vue_insert_form_bulma import vue_insert_form_bulma
    from .examples.vue_update_form import vue_update_form
    from .examples.vue_update_form_bulma import vue_update_form_bulma

The indented ones are inside the `if MODE == full` block.

If I comment the missing imports, the app starts.

Regards.
Maurizio

**Comment by mdipierro** [comment]
this was fixed
