### ISSUE TITLE
ERROR loading showcase app (table "user_token" already exists)

### ISSUE THREAD

**Issue by nicozanf** [web2py/py4web#745]
With a fresh installation with git  (https://py4web.com/_documentation/static/en/chapter-03.html#installing-from-source-locally) at least on Mac, the showcase app cannot start.

It gives:

[FAILED] loading showcase (table "user_token" already exists)

![error](https://user-images.githubusercontent.com/2276743/179047892-7395bc4b-b7fc-4d9a-91ef-2c0f24683bea.png)

**Comment by jpsteil** [comment]
I can confirm this is happening on windows too.

**Comment by nicozanf** [comment]
I've found that the error goes away if you delete all the files inside the _databases_ subfolder....

**Comment by mdipierro** [comment]
Table has been removed from repo

**Comment by mdipierro** [comment]
remove everything in the showcase/databases folder.
