### ISSUE TITLE
Buttons on the main web page are not displayed correctly with Safari

### ISSUE THREAD

**Issue by nicozanf** [web2py/py4web#746]
Using Safari on recent Mac, I've got this strange behaviour moving the mouse over the buttons on the main py4web page:

![safari](https://user-images.githubusercontent.com/2276743/179210208-ec460ac7-5063-40dc-933f-98f4cb67435f.png)

**Comment by mdipierro** [comment]
very very strange  those are just regular html buttons with a border
property

**Comment by nicozanf** [comment]
Maybe it's just my VM, if you do not experiment this problem you can just close the issue

**Comment by mdipierro** [comment]
Closing as recommended
