### ISSUE TITLE
Provide means to turn off the api (localhost:8000/auth/api/all_models etc)

### ISSUE THREAD

**Issue by dlapm** [web2py/py4web#747]
I want to switch off all API links like http://localhost:8000/auth/api/all_models

I included this after my models definition to no effect. Any tips?

```
from pydal.restapi import RestAPI, Policy
policy = Policy()
policy.set('*', 'GET', authorize=False)
policy.set('*', 'PUT', authorize=False)
policy.set('*', 'POST', authorize=False)
policy.set('*', 'DELETE', authorize=False)
```

**Comment by mdipierro** [comment]
Fixed in 3b866c08970ac2d514fdc0bd352a4a8bf3c3f3bf

auth.param.expose_all_models=False
