### ISSUE TITLE
Wait, What?!? Reorganize _scaffold or examples

### ISSUE THREAD

**Issue by MBfromOK** [web2py/py4web#76]
i think we might need to reorganize **apps/_scaffold** or **apps/example**.

I understand that there are probably multiple ways to implement and connect to databases, but we are providing scaffolding as a template or foundation for apps then modelling a different structure / method in the example (with no notation regarding alternative / best practices).

I will probably also propose notations or link to the docs (future friendly, one source to update) for the example files so that beginners like myself will have an easier time catching on to structure flow and the process of getting data into the system, updating, deleting, and displaying the data.

**Common:**

- **__init__.py:** ```from . models import db```

**Uncommon:**

- **examples/models.py:** 
```# define database and tables
db = DAL('sqlite://storage.db', folder=os.path.join(os.path.dirname(__file__), 'databases'))
```
## vs
- **_scaffold/models.py:** ```from . common import db, Field```
 
- **_scaffold/common.py:**
```
from . import settings
db = DAL(settings.DB_URI, 
         folder=settings.DB_FOLDER, 
         pool_size=settings.DB_POOL_SIZE)
```
- **_scaffold/settings.py:**
```
# db settings
APP_FOLDER = os.path.dirname(__file__)
DB_FOLDER = os.path.join(APP_FOLDER, 'databases')
DB_URI = 'sqlite://storage.db'
DB_POOL_SIZE = 1
```

**Comment by mdipierro** [comment]
I am open to reorganization. Notice in scaffold I moved the definition of
db from models to common because of the problem raised here:
https://groups.google.com/d/msg/web2py/VWxhCoAH7m0/m-ZIvqeXBAAJ

**Comment by MBfromOK** [comment]
I feel like I am severely restricted by my level of comprehension to help in a meaningful way here; that said, any help is (hopefully) better than none.

Reading the linked post I am at a loss to provide (very) valuable feedback since I am not sure I am even utilizing sessions (yet).

Does moving the definition of db restrict the apps from accessing their own, unique tables?
Was the issue caused in your linked report because the **```from py4web import *```**  doesn't (or didn't) import sessions?

### It would seem like:
We would want the db settings to be available to be provided both by app and globally to allow setting for the whole py4web tree or by each application

**Comment by MBfromOK** [comment]
Realized I left this out...

Per the referenced docs line 495 should read: (or the class should be restructured)
```
app_name = action().app_name
```
It also looks like we might want to set the initial declaration in the class like this:
__app_name = 'default'

**Comment by mdipierro** [comment]
Make a proposal of how you would reorganize them. The only things I would like to preserve are:
1) a settings.py file
2) a common.py file that can be used by multiple apps and is simple to understand
3) ability to import the app from shell

**Comment by MBfromOK** [comment]
I am not asking (necessarily) for us to get rid of anything, just hoping to help streamline and (as a byproduct) simplify py4web <--> app interaction.

My original intent here was to point out the inconsistency with the recommendation to document a reason why one might method/setup be preferred over another.

After you mentioned the reason that they were different and I started looking into that report the more surprised I became that variables in classes don't work how I thought they did/should.

**Comment by mdipierro** [comment]
I have refactored examples as you suggested. Please check it.

**Comment by MBfromOK** [comment]
Will do!

**Comment by mdipierro** [comment]
Closing. We can reopen if further refactoring is needed.
