### ISSUE TITLE
TypeError: file must have 'read', 'readinto' and 'readline' attributes

### ISSUE THREAD

**Issue by tarvos21** [web2py/py4web#77]
I encounter the same errors for many times, pip install(then I try to install from source and succeed), realod apps in the dashboard, what may be the problem?
```
/pydal/migrator.py", line 300, in create_table
    sql_fields_old = pickle.load(tfile)
TypeError: file must have 'read', 'readinto' and 'readline' attributes
```

I use python 3.8 on macOS Catalina. Thanks!

**Comment by mdipierro** [comment]
This may fix it 603b8e0eb6ef026d8beff13c472d91bca1ddbe5c please try it.

**Comment by tarvos21** [comment]
when I 'git checkout <sha>', I got:
`fatal: reference is not a tree: 603b8e0eb6ef026d8beff13c472d91bca1ddbe5c`

**Comment by tarvos21** [comment]
when I run `make test`, I got 2 errors, will that influence it?

I could get into the dashboard, but some apps are warning(red)

**Comment by mdipierro** [comment]
Problem is you have python3.8. py4web was not tested with 3.8. will fix
tonight

**Comment by tarvos21** [comment]
I got it. Thanks!

**Comment by mdipierro** [comment]
sorry this is taking longer than expected. There are more problem with py3.8 and I am unhappy they broke backward compatibility again.

**Comment by tarvos21** [comment]
OK, thanks, I will close this, but still intensely follow py4web and web2py progress.

**Comment by mdipierro** [comment]
I will prioritize support for 3.8. :-)
