### ISSUE TITLE
uploading file - issue with form when not accepted

### ISSUE THREAD

**Issue by Digitropics** [web2py/py4web#770]
The problem I'm having is with required fields when also using the upload file Field.

Let's say I'm filling a form, in which I choose a file.
Now, if I miss one of the field that is required and I click "Submit", the chosen file name disappears (annoying, I'm expecting it to remain like any other fields) and also I'm getting a "Currently: download" with a link to nowhere (actually, a link to ../static/#)

Some screenshots:

Original screen (position is set as IS_NOT_EMPTY):

![screenshot23-01-10_14-40-28](https://user-images.githubusercontent.com/122340049/211471971-df408b3f-4f78-4724-9ef7-0e22638aefdc.png)

Just before clicking "Submit" (I omitted position on purpose):

![screenshot23-01-10_14-43-00](https://user-images.githubusercontent.com/122340049/211472078-a83140a8-0889-431f-9f35-e45304e32e1b.png)

After I clicked "Submit":

![screenshot23-01-10_14-44-55](https://user-images.githubusercontent.com/122340049/211472192-7452e199-7d2d-4b6d-b3bb-a459ddf33d79.png)

**Comment by mdipierro** [comment]
Posted a fix to master. Can you please confirm it works well for you? If so I will release a new py4web version.
