### ISSUE TITLE
Email addresses are case-sensitive / can be compared by == or strcmp

### ISSUE THREAD

**Issue by manuelep** [web2py/py4web#773]
https://github.com/web2py/py4web/blob/f6bab4d8ce9c6fde0bd4fa41a5e39a8a84726a90/py4web/utils/auth.py#L525

If it's true that "e-mails are case sensitive" (source: https://beesbuzz.biz/code/439-Falsehoods-programmers-believe-about-email) why the value in this line is changed using the lower method?

Thanks

**Comment by ali96343** [comment]
https://stackoverflow.com/questions/9807909/are-email-addresses-case-sensitive
no widely used mail systems distinguish different addresses based on case.

**Comment by mdipierro** [comment]
I agree we should threat as case insensitive because in practice they are.
