### ISSUE TITLE
Bug in Form when check box "check to delete" is checked. 

### ISSUE THREAD

**Issue by ch-rigu** [web2py/py4web#777]
Hi, I'm having a bug when I try to delete a record with the check box "check to delete", when is checked and then submit form, it works, the record is being deleted but not marked as "accepted" is marked as "not accepted". I need to redirect to another page after deletion of the record but I does not work. If the redirection is in the "else" condition, it works but also redirect everytime that I try to see the record..

model.py
db.define_table('archivos', 
                Field('folio_proyecto', 'string'),
                Field('name', 'string'),
                Field('archivo', 'upload', upload_path=UPLOAD_FOLDER, download_url = lambda filename: URL('download/%s' % filename)),
                Field('fecha', 'datetime', default=datetime.datetime.now()),
                )
                
                
form_file = Form(db.archivos,record=record,deletable=True, formstyle=FormStyleDefault)
if form_file.accepted:
   redirect(URL('ver_proyecto',folio))
else:
    print('not accepted')

Cheers.

**Comment by cdb88** [comment]
You should check form.deleted to see if a record has been deleted, it works differently than web2py.

You can see it here:
https://groups.google.com/g/py4web/c/gZF4QzRCmNA/m/bm9q4R1PCwAJ

**Comment by ch-rigu** [comment]
Closing because is not a bug.
