### ISSUE TITLE
py4web documentation 'search' not working

### ISSUE THREAD

**Issue by davidmanns** [web2py/py4web#783]
see https://groups.google.com/d/msgid/py4web/4679edae-bb00-4e71-aee9-3f8f8e72bdb2n%40googlegroups.com?utm_medium=email&utm_source=footer

**Comment by mrworm** [comment]
There is at least in Windows a few more steps needed but the:
cd docs
pip install --upgrade -r requirements.txt
gives you plenty of hints of the issues. 
And the biggest issue I had to get it to work was the missing (old) visual studio (latest one could not handle the build fully):
https://visualstudio.microsoft.com/af5d2e5f-18b8-450f-923a-52f595c61631
Check the option:
Desktop Development with C++
Run the installer then again to see if it is successful.
And then you can copy the missing files that you find from F12 in dev options of your browser from different places, note that the path is slightly different from  https://nicozanf.github.io/py4web-doc/en/master/index.html 

But I got it to work!

**Comment by nicozanf** [comment]
Now the online Search is working fine, so we can close this issue ;-)
