### ISSUE TITLE
py4web: URL Prefix, _dashboard relative path in dbadmin.js

### ISSUE THREAD

**Issue by Apsolon** [web2py/py4web#785]
Hi,

testing with pre-fix with David Rosalia we stumble upon issue while try to edit/view DB in _dashboard we fixed this by making url path in 
app.data relative in dbadmin.js on line 7 like this:

app.data.url = '../rest/{app}/{dbname}/{tablename}'.format(app.data);

prehaps it could be refined with implicit prefix included instead but this works like a charm,

could you please include this fix :)

thank you very much

**Comment by mdipierro** [comment]
This was fixed some time ago. Thanks.
