### ISSUE TITLE
How to set server own email to send verification link for newly registered user?

### ISSUE THREAD

**Issue by mahbubcubd** [web2py/py4web#82]
Hi, we were running a py4web app named bipolarai  under this domain bipolar.ai.  We are running it with uwsgi and Nginx. I was finding the section to send the user registration verification link. Because users are getting 'verification pending' alert when they are going to log in after a successful registration. How I can provide them the verification link? Please help.

**Comment by mdipierro** [comment]
Posted an example https://github.com/web2py/py4web/blob/master/apps/_scaffold/settings.py#L18

**Comment by mdipierro** [comment]
thanks bringing this up. I overlooked it.

**Comment by mahbubcubd** [comment]
Thank You So Much

**Comment by mdipierro** [comment]
Please let us know if you find any problem.

**Comment by mahbubcubd** [comment]
Dear Massimo,
I have set up the email configuration like your last commit with my SMTP
server email's credentials. But after registering, user are not getting
their verification link to their email from my server email address.Well, I
am getting the access token link in uwsgi log. I don't know what to do now.
I was finding the function which is actually sending mail after the from
post.
Please help
Thank You
