### ISSUE TITLE
PyDAL: Bulk Insert

### ISSUE THREAD

**Issue by MBfromOK** [web2py/py4web#83]
Reading through the PyDAL docs and learning about how to insert and update data efficiently...

I see this:

> py4web also provides a bulk_insert method:
> `>>> db.person.bulk_insert([{'name': 'Alex'}, {'name': 'John'}, {'name': 'Tim'}])`

It further states:
> It takes a list of dictionaries of fields to be inserted and performs multiple inserts at once

I have a dictionary (of dictionaries) full of entries like the following that I have since converted to a list of dictionaries to try and make this work: 
{'EmployeeID': 'xxxxx', 'Department': 'XYZ Department', 'DisplayName': 'Person, Test', 'GivenName': 'Test', 'Surname': 'Person', 'IPPhone': '73509', 'telephoneNumber': '900-857-3509', 'mail':  email@mydomain.org', 'Attribute9': 'TUVWX'}

The issue I am running into is that the 'DisplayName': 'LastName, FirstName' breaks the import for each line and no fields import after this one.

Additionally, is there a way to pass a field map/list to this function? - (To map unlike fieldnames to db)

**Comment by mdipierro** [comment]
This is more of a pydal question than an issue. I will close issue. Please ask the question on the web2py mailing list. Can you also provide a minimal example of model and insert to reproduce the problem?
