### ISSUE TITLE
-A or --app_names ignored on watch sync and file changed.

### ISSUE THREAD

**Issue by marvin4ward** [web2py/py4web#919]
I start `py4web` app with `-A` limiting only for a single app with `--watch sync` and after any `py` file changed `py4web` reloads including apps that were not allowed with `-A` parameter.

**Comment by mdipierro** [comment]
please open a ticket about this

**Comment by mdipierro** [comment]
I think it is now fixed. Can you please check?

**Comment by marvin4ward** [comment]
The issue looks resolved. By the way - running app from py4web repo did not reproduce the issue, while running with pip module did. 
Thank you for quick resolution.

**Comment by mdipierro** [comment]
yes. i need to publish a new pypi package for pip to work. thanks for
checking
