### ISSUE TITLE
py4web website does not seem to be running the most recent version

### ISSUE THREAD

**Issue by kszys** [web2py/py4web#927]
The [documentation on the py4web website](https://py4web.com/_documentation/static/en/index.html) seems to be a few versions old... Perhaps it would be useful for it point the newest version instead?

**Comment by mdipierro** [comment]
yes. i will automate the doc update

**Comment by mdipierro** [comment]
deployed new docs.

**Comment by kszys** [comment]
Hmm... I still seem to be seeing the old version there at https://py4web.com/_documentation/static/en/index.html

**Comment by mdipierro** [comment]
Fixed. for now.
