### ISSUE TITLE
Python 3.13: ModuleNotFoundError: No module named 'cgi'

### ISSUE THREAD

**Issue by nicozanf** [web2py/py4web#928]
With python 3.13.0, you've got this error message when trying to run py4web.

It seems that the cgi and cgitb modules, deprecated in Python 3.11, has just been removed (see similar problems with [Cherrypy](https://github.com/cherrypy/cherrypy/issues/2014) ). I'm attaching the [error obtained](https://github.com/user-attachments/files/17328675/cgi_error.txt) - I think it's related to the ombott module.

**Comment by mdipierro** [comment]
fixed. thank you!
