### ISSUE TITLE
pydal upgrade is breaking legacy _scaffold app

### ISSUE THREAD

**Issue by gersios** [web2py/py4web#948]
```
    from utils import utcnow
ImportError: cannot import name 'utcnow' from 'utils' (/home/user/.local/lib/python3.7/site-packages/utils/__init__.py)
[FAILED] loading _scaffold (cannot import name 'utcnow' from 'utils' (/home/user/.local/lib/python3.7/site-packages/utils/__init__.py))

```

**Comment by nicozanf** [comment]
Please provide python, py4web and pydal version.
Is it Linux, I suppose, right?
Does the error occur just at startup of py4web or by visiting the _scaffold app?
Does the error disappear just downgrading pydal?

thanks for the feedback

**Comment by nicozanf** [comment]
Confirmed also on Ubuntu, latest py4web from github = 1.20240915.1 and python  3.12.7 ;-( Same error on apps: fadebook and tagged_posts.

Downgrading pydal with "pip3 install pydal==20241111.2" fixes the problem
