### ISSUE TITLE
py4web 404 on ubuntu for windows

### ISSUE THREAD

**Issue by JoeCodeswell** [web2py/py4web#96]
Hi folks, I am trying to run py4web on ubuntu for windows.

RESULT:  http://127.0.0.1:8000/  yields ORANGE & WHITE "404 NOT FOUND"

I will attach  _py4web_install_log_notes.md.txt
[_py4web_install_log_notes.md.txt](https://github.com/web2py/py4web/files/3970014/_py4web_install_log_notes.md.txt)

This is SO exciting.

Love and peace,
Joe Dorocak

**Comment by JoeCodeswell** [comment]
Hi folks,

This is a note regarding the contents of [_py4web_install_log_notes.md.txt](https://github.com/web2py/py4web/files/3970014/_py4web_install_log_notes.md.txt)

The first half of the file is dedicated to upgrading my ubuntu on windows packages. 
If you search for "# install [py4web](https://github.com/web2py/py4web#py4web) ", that's where the py4web install begins.

Thanks again.
Love and peace,
Joe

**Comment by JoeCodeswell** [comment]
Just looked at the apps folder - there was nothing in there.
```
$ cd apps
$ ls
__init__.py  __pycache__
$ ```
I'll download some stuff from the repo & try again.

**Comment by JoeCodeswell** [comment]
loaded the apps folder from the master 
ran `pfw1Pj$ py4web-start  127.0.0.1:8000 -d apps`
browsed to http://127.0.0.1:8000/_dashboard
here is the resulting screenshot

![Clipboard01](https://user-images.githubusercontent.com/3194021/71007756-62a21d80-209c-11ea-8289-83843ea7e544.jpg)

**Comment by mdipierro** [comment]
It is py4web-start apps no -d

**Comment by JoeCodeswell** [comment]
### Much better. Thanks, Massimo.

``` bash
joe@joethinks:/mnt/c/1d/PythonPjs/Py4webPjs/pfw1Pj$ py4web-start apps 

██████╗ ██╗   ██╗██╗  ██╗██╗    ██╗███████╗██████╗
██╔══██╗╚██╗ ██╔╝██║  ██║██║    ██║██╔════╝██╔══██╗
██████╔╝ ╚████╔╝ ███████║██║ █╗ ██║█████╗  ██████╔╝
██╔═══╝   ╚██╔╝  ╚════██║██║███╗██║██╔══╝  ██╔══██╗
██║        ██║        ██║╚███╔███╔╝███████╗██████╔╝
╚═╝        ╚═╝        ╚═╝ ╚══╝╚══╝ ╚══════╝╚═════╝ 
Is still experimental...

Dashboard is at: http://127.0.0.1:8000/_dashboard  
[X] loaded 127.0.0.1:8000     
[X] loaded examples     
[X] loaded todo     
[X] loaded _dashboard     
[X] loaded _default     
[X] loaded _documentation     
[X] loaded _minimal           
[X] loaded _scaffold     
Bottle v0.12.18 server starting up (using TornadoServer())...
Listening on http://127.0.0.1:8000/
Hit Ctrl-C to quit.

WARNING:tornado.access:404 GET /favicon.ico (127.0.0.1) 2.88ms
```

![Clipboard02](https://user-images.githubusercontent.com/3194021/71187298-a8ddb500-2233-11ea-9128-7412c3e2fa48.jpg)
